This layer provides calculated status values for the economies subgoal.  Economies is calculated using revenue data from marine sectors. 

Note: These data are no longer supported.  Consequently, this layer was last updated in 2013, and this goal will no longer be updated with these data.

Economies status is  calculated as:
(cur_base_value / ref_base_value) / (cur_adj_value / ref_adj_value)

Where, cur_base_value is the most recent revenue values for each sector/region, and ref_base_value is the earliest year of revenue data for each sector/region.  These values are adjusted by dividing by the GDP of corresponding region/year to control for larger economic trends. National GDP data were obtained from the World Bank ([http://data.worldbank.org/indicator/ NY.GDP.MKTP.CD](http://data.worldbank.org/indicator/ NY.GDP.MKTP.CD)).  These data were used in economy subgoal to adjust revenue data. For the three EEZs that fall within the China region (China, Macau, and Hong Kong), we combined the values using a population-weighted average.

This layer includes yearly data for revenue in commercial fishing, aquarium trade fishing, mariculture, marine mammal watching, marine renewable energy, and, tourism. The data sources and methods for each sector are described below.

#### Aquarium trade fishing
To approximate revenue from aquarium fishing we used export data from the FAO Global Commodities database for ‘Ornamental fish’ for all available years. We used data from two of the four subcategories listed, excluding the subcategory ‘Fish for culture including ova, fingerlings, etc.’ because it is not specific to ornamental fish, and the subcategory ‘Ornamental freshwater fish’ because it is not from marine systems.

#### Commercial fishing
Revenue data for commercial fishing were obtained from FAO’s FishStat database, which provides yearly dollar values of commercial fisheries production for marine, brackish and freshwater species starting in 1950 and updated yearly.  To isolate production values attributable to marine and brackish aquaculture, data pertaining to freshwater species were omitted. This species classification process was very time consuming as each species had to be queried individually per year. There was little year-to year variation, and thus data were extracted in 5 year increments, providing data for 1997, 2002 and 2007.

#### Mariculture
Data on revenues from marine aquaculture were derived from FAO’s FishStat database, which includes country-level data on total production values for marine, brackish, and freshwater species beginning in 1984 and updated yearly. To isolate production values attributable to marine and brackish aquaculture, data pertaining to freshwater species were omitted. This species classification process was very time consuming as each species had to be queried individually per year. There was little year-to year variation, and thus data were extracted in 5 year increments, providing data for 1997, 2002 and 2007.

#### Marine mammal watching
IFAW (see **`r layer_meta$name[layer_meta$layer == 'le_jobs_sector_year']`** layer) provides time series (for at least four years between 1991 and 2008), country-level data on total expenditures (including direct and indirect) attributable to the whale watching industry (O'Connor et al. 2009). Here, total expenditures are used as a close proxy for total revenue. We used total expenditure data (direct and indirect expenditures) to avoid using a literature derived multiplier effect. When IFAW reported “minimal” revenue from whale watching, we converted this description to a 0 for lack of additional information. For countries with both marine and freshwater cetacean viewing, we adjusted by the proportion of marine revenue as described for the jobs dataset.

#### Marine renewable energy
The United Nations Energy Statistics Database provides production data, in kilowatt-hours (KWh), for tidal and wave electricity. However, only two countries, France and Canada, have high enough levels of production to be reported in this data source. For Canada, production data were replaced with production data (Gross Megawatt hours per year from 1995-2010) provided directly from the Annapolis tidal power plant because the plant provided a longer time series (Ruth Thorbourne, personal communication, Aug 9, 2011). To convert production data into revenue, production values were multiplied by average yearly prices of electricity per KWh specific to Canada and France, provided by the US Energy Information Administration ([http://www.eia.gov/emeu/international/elecprii.html](http://www.eia.gov/emeu/international/elecprii.html); updated June 2010) after conversion to 2010 USD. Some of the production data could not be used because there were no available electricity price data to convert production into revenue, truncating our time series.

#### Tourism 
WTTC (see **`r layer_meta$name[layer_meta$layer == 'le_jobs_sector_year']`** layer) reports time series data on the dollar values of visitor exports (spending by foreign visitors) and domestic travel and tourism spending; combining these two data sets creates a proxy for total travel and tourism revenues. WTTC was chosen as the source for tourism revenue data because of the near-complete country coverage, the yearly time series component starting in 1988 and updated yearly, and the inclusion of both foreign and domestic expenditures. This dataset lumps inland and coastal/marine revenues, and so was adjusted by the percent of a country’s population within a 25 mile inland coastal zone. We included no projected data. We used total contribution to GDP data (rather than direct contribution to GDP) to avoid the use of literature derived multiplier effects.