*Resilience*

*Category: ecological/regulatory*

*Subcategory: fishing*

These data describe the current effectiveness of fisheries management regimes along 6 axes (Mora et al. 2009): scientific robustness, policy transparency, implementation capacity, subsidies, fishing effort, and foreign fishing. All countries with coastal areas were assessed through a combination of surveys, empirical data and enquiries to fisheries experts. For each OHI reporting region, scores for each category were rescaled between 0 and 1 using the maximum possible value for each category and then the average score of all 6 categories was used as the overall fisheries management effectiveness score.

Data are not accessible in csv format from website, so points were manually entered into excel and saved as a csv (found in v2019/raw). Because FMI scores only exist for 40 out of the 220 OHI regions, we trained linear models using scores from the AO need layer (rescaled GDP per capita per person purchasing power), GDP per capita, World Governance Index (WGI), Social Progress Indicator (SPI), and UN georegion labels to determine which would be most effective for gapfilling the missing data. After comparing the models, we determined SPI and UN georegions to be the best predictors of FMI, and used these models to gapfill FMI scores for the remaining 80 regions. 20 of these regions remain NA as they are uninhabited.


# Data used to gapfill missing FMI data points

## SPI

*Note: These data were not updated for v2019 at the time of completing the FMI resilience layer.*

**Citation**: http://www.socialprogress.org/

Stern, S., A. Wares and T. Epner. 2018. Social Progress Index: 2018 Methodology Report.

**Source information**: 
http://www.socialprogress.org/ --> Download Data

**Date Downloaded**: 9/21/2018

**Time range**: 2014-2018

**Native data resolution**: country scores

**Format**:  Excel file

**Description**: Social Progress Index scores and components for countries.


## UN georegions

UNgeorgn() loads a dataframe from common.R with UN geopolitical designations, and is commonly used in OHI to gapfill missing data. The distinct regions are derived from the [United Nations Statistics Division](https://unstats.un.org/unsd/methodology/m49/)Each region is assigned four labels with increasing granularity/specificity: r0_label = World (1 level), r1_label = continental regions (7 levels: Oceania, Asia, Africa, Europe, Southern Islands, Latin America and the Caribbean, and Americas), r2_label = georegions (22 levels for subregions and intermediary regions).
