#### Salt marsh 
Saltmarsh data are used to calculate the coastal proection and carbon storage goals, and the habitat subgoal.

Salt marsh extent area (km^2^) comes from multiple sources (Bridgham et al. 2006, Dahl 2000, Ministry for the Environment 2007, JNCC 2004, EEA 2008).  In the case of Europe, most data were obtained via the European Environment Agency databases housing information pertaining to the European Union's Habitat Directive.  

Severe data gaps exist for several key regions of the world, including the Middle East, South America, and Africa. Extensive salt marshes are believed to exist in the Middle East, bordering the unique salt flat ecosystems known as sabkha, however no numbers concerning extent could be found. Similarly, data on salt marshes in South America were extremely limited, with no estimates on current rates of loss or historical extent from or before the 1970s. The majority of the data included in the model come from North America (United States and Canada), Australia, New Zealand, China, Europe, and the United Kingdom.
