*Pressure*

*Category: ecological*

*Subcategory: pollution*

This pressure layer is calculated using modeled data for land-based organic pollution (pesticide data), land-based inorganic pollution (using impermeable surfaces as a proxy), and ocean pollution (shipping and ports). These global data are provided at ~1km resolution, with raster values scaled from 0-1 (Halpern et al. 2008, 2015). To obtain the final pressure values, the three raster layers were summed (with cell values capped at 1).   

#### Land-based organic pollution
Data were calculated using modeled plumes of land-based pesticide pollution that provide intensity of pollution at 1km^2^ resolution (Halpern et al. 2008). 

Organic pollution was estimated from FAO data on annual country-level pesticide use ([http://faostat3.fao.org/faostat-gateway/go/to/browse/R/*/E](http://faostat3.fao.org/faostat-gateway/go/to/browse/R/*/E)), measured in metric tons of active ingredients.  FAO  uses survey methods to measure quantities of pesticides applied to crops and seeds in the agriculture sector, including insecticides, mineral oils, herbicides, fungicides, seed treatments insecticides, seed treatments fungicides, plant growth regulators and rodenticides. Missing values were estimated by regression between fertilizer and pesticides when possible, and when not possible with agricultural GDP as a proxy.  Data were summed across all pesticide compounds and reported in metric tons. Upon inspection the data included multiple 0 values that are most likely data gaps in the time-series, so they were treated as such and replaced with NA. In addition, regions with only 1 data point and regions where the most recent data point was prior to 2005 were excluded. Uninhabited countries were assumed to have no pesticide use and thus excluded. 

Region-level pollution values were then dasymetrically distributed over a region’s landscape using global landcover data from 2009, derived from the MODIS satellite data at ~500m resolution. These values were then aggregated by ~140,000 global basins, and diffusive plumes were modeled from each basin’s pourpoint. The final non-zero plumes (about ~76,000) were aggregated into ~1km Mollweide (wgs84) projection rasters to produce a single plume-aggregated pollution raster. 

These raw values were then ln(X+1) transformed and normalized to 0-1 by dividing by the 99.99th quantile of raster values across all years.  The zonal mean was then calculated for each region.  

#### Land-based inorganic pollution
These data are from Halpern et al. (2008, 2015), and available from Knowledge Network for Biocomplexity (KNB, [https://knb.ecoinformatics.org/#view/doi:10.5063/F19021PC, rescaled_2013_inorganic_mol](https://knb.ecoinformatics.org/#view/doi:10.5063/F19021PC, rescaled_2013_inorganic_mol)). Non-point source inorganic pollution was modeled with global 1 km^2^ impervious surface area data [http://www.ngdc.noaa.gov/dmsp/](http://www.ngdc.noaa.gov/dmsp/) under the assumption that most of this pollution comes from urban runoff. These data will not capture point-sources of pollution or nonpoint sources where paved roads do not exist (e.g., select places in developing countries). Values were aggregated to the watershed and distributed to the pour point (i.e., stream and river mouths) for the watershed with raster statistics (i.e., aggregation by watershed).

#### Ocean pollution (shipping lanes, ports)
These data are from Halpern et al. (2015), and available from the Knowledge Network for Biocomplexity (KNB, [https://knb.ecoinformatics.org/#view/doi:10.5063/F1DR2SDD](https://knb.ecoinformatics.org/#view/doi:10.5063/F1DR2SDD), rescaled_2013_one_ocean_pollution_mol). Ocean-based pollution combines commercial shipping traffic data and port data.  

Shipping data was obtained from two sources:  (1) Over the past 20 years, 10-20% of the vessel fleet has voluntarily participated in collecting meteorological data for the open ocean, which includes location at the time of measurement, as part of the Volunteer Observing System (VOS). (2) In order to improve maritime safety, in 2002 the International Maritime Organization SOLAS agreement required all vessels over 300 gross tonnage (GT) and vessels carrying passengers to equip Automatic Identification System (AIS) transceivers, which use the Global Positioning System (GPS) to precisely locate vessels.  

Port data was based on the volume (measured in tonnes) of goods transported through commercial ports as a proxy measure of port traffic. Total cargo volume data by port was collected from regional and national statistical organizations, and from published port rankings.  