AO.Rmd -- Ning works on this

### Goal Description

Artisanal fishing, often also called small-scale fishing, provides a critical source of food, nutrition, poverty alleviation and livelihood opportunities for many people around the world, in particular in developing nations. This goal measure whether people who need to fish on a small, local scale have the opportunity to do so. It has three sub-components: stock, access, and need. A score of 100 means the country or region is meeting the needs of artisanal fishermen or communities by implementing institutional supports, providing access to near-shore water, and maintaining the health of targeted species. 

**For Global assessments....** 

### Model & Data 

The AO model assesses ...:   
Below are the data sets for this goal.

### Reference points 

Reference point is ....

## This is now AO.Rmd -- Mel

**Status and Trend:**

- [Artisanal fisheries management effectiveness and opportunity] (go to the layers.html#ao_need, where there's more description,  whether it was updated in that year, relevant refs, link to data prep) (some day, info about gapfilling)
Accompanying text: The opportunity for artisanal and recreational fishing based on the quality of management of the small-scale fishing sector

**Pressures:**  

**Resilience:** 




