### Goal Description

The Carbon Storage goal captures the ability of the coastal habitats to remove carbon given their carbon uptake rate and health conditions. A score of 100 means all habitats that contribute to carbon removal are still intact or have been restored and they can function to their full carbon burial potential. Highly productive coastal wetland ecosystems or seagrass store substantially large amount of carbon have the highest sequestration rates of any habitats on earth. They are also threatened by under-regulated coastal development but are amenable to restoration and conservation efforts. 

**For Global assessments....** 

### Model & Data 

Goal model measures the current ‘condition’ of habitats relative to reference conditions, weighted by the relative contribution of each habitat type to total carbon sequestration, using data from (Laffoley & Grimsditch 2009). Habitat conditions are represented by their coverage area. 

Three coastal habitats known to provide meaningful amounts of carbon storage were included in this goal: mangroves, seagrasses, and salt marshes (Halpern 2012).

Below are the data sets for this goal.

### Reference points 

Reference point is ....

## This is now AO_layers.Rmd -- Mel

**Status and Trend:**

- [Artisanal fisheries management effectiveness and opportunity] (go to the layers.html#ao_need, where there's more description,  whether it was updated in that year, relevant refs, link to data prep) (some day, info about gapfilling)
Accompanying text: The opportunity for artisanal and recreational fishing based on the quality of management of the small-scale fishing sector

**Pressures:**  

**Resilience:** 




