### Goal Description

Habitats conditions are considered as a proxy for condition of the broad suite of species that depend on them. The Habitats sub-goal includes all habitats in the study area, and assess their health condition and coverage area.

### Model & Data 

The Habitat model assessed all habitats for which at least some global data were available, specifically: mangroves, coral reefs, seagrass beds, salt marshes, sea ice edge, and subtidal soft-bottom habitats. Status was calculated as the average of the condition estimates for each habitat present in a region, measured as the loss of habitat and/or percent degradation of remaining habitat. 

Below are the data sets for this goal.

### Reference points 

Reference point is ....

## This is now AO_layers.Rmd -- Mel

**Status and Trend:**

- [Artisanal fisheries management effectiveness and opportunity] (go to the layers.html#ao_need, where there's more description,  whether it was updated in that year, relevant refs, link to data prep) (some day, info about gapfilling)
Accompanying text: The opportunity for artisanal and recreational fishing based on the quality of management of the small-scale fishing sector

**Pressures:**  

**Resilience:** 




