### Goal Description

Mariculture measures the ability to reach the highest levels of seafood gained from farm-raised facilities without damaging the ocean’s ability to provide fish sustainably now and in the future. Higher scores reflect high food provisioning in a sustainable manner, while not compromising the water quality in the farmed area and not relying on wild populations to feed or replenish the cultivated species. A score of 100 means that a region is sustainably harvesting the greatest amount of farmed seafood possible based on its own potential.

### Model & Data 

The Status of the Mariculture subgoal (xMAR), was defined as production of strictly marine species from both the marine and brackish water FAO categories, excluding aquatic plants such as kelps and seaweeds, which were assumed to contribute predominantly to medicinal and cosmetic uses rather than as a source of food (Halpern 2012). 

Model measures the quantity of sustainably harvested mariculture species per coastal inhabitant (i.e., those within 25km of the coast), under the assumption that mariculture development scales proportionally with coastal population, which is a proxy for potential logistic limitations to farm development, e.g., presence of infrastructures, coastal access, and locally available workforce. The sustainability score (SM,k) for each species in each country is based on the Mariculture Sustainability Index (MSI) (Halpern 2015).

### Reference points 

Reference point is ....

## 

**Status and Trend:**

- [Artisanal fisheries management effectiveness and opportunity] (go to the layers.html#ao_need, where there's more description,  whether it was updated in that year, relevant refs, link to data prep) (some day, info about gapfilling)
Accompanying text: The opportunity for artisanal and recreational fishing based on the quality of management of the small-scale fishing sector

**Pressures:**  

**Resilience:** 




