### Goal Description

In many countries the harvest of non-food natural products is important for local economies and can also be traded internationally. The sustainable harvest of these products is therefore an important component of a healthy ocean. This goal assesses the ability of countries to maximize the sustainable harvest of living marine resources, such as corals, shells, seaweeds, and fish for the aquarium trade. It does not include bioprospecting which focuses on potential (and largely unknowable and potentially infinite) value rather than current realized value, or non-living products such as oil and gas or mining products which by definition are not sustainable.

**For Global assessments....** 

### Model & Data 

The AO model assesses ...:   
Below are the data sets for this goal.

### Reference points 

Reference point is ....

## This is now AO_layers.Rmd -- Mel

**Status and Trend:**

- [Artisanal fisheries management effectiveness and opportunity] (go to the layers.html#ao_need, where there's more description,  whether it was updated in that year, relevant refs, link to data prep) (some day, info about gapfilling)
Accompanying text: The opportunity for artisanal and recreational fishing based on the quality of management of the small-scale fishing sector

**Pressures:**  

**Resilience:** 




