### Goal Description

Tourism and recreation in coastal areas is a major component of thriving coastal communities and a measure of how much people value ocean systems, i.e. by traveling to coastal and ocean areas. This goal aims to capture the number of people, and the quality of their experience, visiting coastal and marine areas and attractions. A score of 100 means a region utilizes its full recreational potential without harming the ecosystem.

### Model & Data 

Assuming that the total number of people engaged in coastal tourism and recreation activities is directly correlated with employment in the tourism sector (eg. accommodation services, food and beverage services, retail trade, transportation services, and cultural, sports and recreational services), the TR model measures the proprotion of employment in tourism relative to total labor force in each country. The model also incorporated tourism competitiveness index (TTCI) from the World Economic Forum (WEF 2013) to capture the sustainability of the tourism
industry (Halpern 2015). 
   
Below are the data sets for this goal.

### Reference points 

Reference point is ....

## This is now AO_layers.Rmd -- Mel

**Status and Trend:**

- [Artisanal fisheries management effectiveness and opportunity] (go to the layers.html#ao_need, where there's more description,  whether it was updated in that year, relevant refs, link to data prep) (some day, info about gapfilling)
Accompanying text: The opportunity for artisanal and recreational fishing based on the quality of management of the small-scale fishing sector

**Pressures:**  

**Resilience:** 




