---
layout: article
title: "About"
excerpt: "This is the about page."
image:
  feature:
  teaser:
  thumb:
share: false
ads: false
---

A healthy ocean sustainably delivers a range of benefits to people now and in the future.

While the Ocean Health Index framework was first demonstrated at the global scale (Halpern _et al._ 2012, _Nature_), assessments conducted at smaller spatial scales provide a clearer picture of local ocean health. Using existing data, indicators and priorities, **Ocean Health Index <i class="fa fa-search-plus"></i> subcountry assessments** combine local elements influencing ocean health at the spatial scales where policy and management decisions are made.  

To enable and facilitate independent groups interested in conducting Ocean Health Index <i class="fa fa-search-plus"></i> subcountry assessments, we provide a suite of information, software, and guidance on this website. Since small-scale assessments often occur at the country-level, this website includes a template for each coastal country, including subcountry divisions (often coastal states or provinces) populated with data and models used in the global assessment.  

We encourage any group to use this website as a starting point, incorporating local data, models, and priorities to to the template we provide.


## Contact

For more information:  

- [OceanHealthIndex.org](http://www.oceanhealthindex.org)  

For strategic guidance:

- epacheco at conservation dot org  

For technical guidance:

- lowndes at nceas.ucsb.edu
