---
title: "Download data and methods"
output: 
  html_document:
     includes: 
      in_header: '~/github/ohiprep/src/templates/ohi_hdr.html'
---

```{r setup, echo=F, warning=FALSE, message=F}
source("./_site.R")
```
<!---From http://stackoverflow.com/questions/31753897/2-column-section-in-r-markdown:
Put in your css file or directly in rmarkdown--->
<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
</style>

<br>
Global assessments require synthesizing highly heterogeneous information that is freely available from nearly one hundred sources. Data from each source are prepared and modeled using freely available coding and version control software. You may freely download and use any data, code, or instructional guides, but please see our [Citation policy](http://ohi-science.org/citation-policy/).  

With each annual global assessment we have incrementally improved data processing and modeling methods based on new information, knowledge, and feedback. Thus, for annual scores to be comparable with previous years, we recalculate previous assessments with the most recent methods for each past assessment year. All code and most data are available online on GitHub.  

-----

<div class="col2">
**Global assessment scores**

Quick access to *.csv* files of calculated global scores.  
Select a year and right-click to Save As. View the [metadata for these files](https://github.com/OHI-Science/ohi-global/blob/draft/global2016/Reporting/data).
<!----TODO: an md with header info. Mel will make this as a README, with lookup --->

- [2012](https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/global2016/Reporting/data/scores_eez2012.csv)
- [2013](https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/global2016/Reporting/data/scores_eez2013.csv)
- [2014](https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/global2016/Reporting/data/scores_eez2014.csv)
- [2015](https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/global2016/Reporting/data/scores_eez2015.csv)
- [2016](https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/global2016/Reporting/data/scores_eez2016.csv)

**Full methods and data**

We do annual 'releases', which include the newest methods for current and previous years.

- [data preparation releases (`ohiprep`)](https://github.com/OHI-Science/ohiprep/releases) <!---TODO: change link Mel will move globalprep into a new repo: ohi-global-prep --->
- [score calculation releases (`ohi-global`)](https://github.com/OHI-Science/ohi-global/releases)
- [scores are calculated with the `ohicore` R package](https://github.com/OHI-Science/ohicore)
- COMING SOON: shapefiles, including global regions
<br>
</div>

<br>
**Documentation and Instruction**

• [Peer-reviewed publications](http://ohi-science.org/resources/publications/) • [Assessment Manual (including how to use `ohicore`)](http://ohi-science.org/manual)

---- 

## Acknowledgements

We thank all the groups that collect and share data openly; please see the [global layers page](https://github.com/OHI-Science/ohi-global/layers.html) for a full list. We also thank developers that make and teach free software tools, in particular [R](https://cran.r-project.org/), [RStudio](https://www.rstudio.com), [git](https://git-scm.com/), and [GitHub](https://github.com/). 

