---
title: "Frequently Asked Questions (FAQ)"
output:
  html_document:
    toc: true
---

## What does "Scenario" mean?

The **scenario** refers to the name of a given scenario. This starter kit begins with the "subcountry2014" data to indicate that data was extracted from the OHI global analysis at a subcountry level where possible. A new scenario could be started by a simple copy and paste of the subcountry2014 and then modification to any of the files. The name of the scenario could be any you desire. For instance, we envision alternate scenarios could be created to illustrate the effects on ocean health of various proposed policies.

## Is this all free?

Yes! We are promoting the ethos of using publicly available data, whenever possible, and using freely available software. All the data to get started is wrapped up in a single Github repository. As long as the repository is maintained as a public repository the website and data are free to host there. The real investment is in customizing these files to suit the needs of your own country.
