---
title: "Ocean Health Index Fellows Program"
subtitle: "Training the next generation of ocean data scientists through global ocean health assessments"
output:
  html_document
---

<picture here?>


OHI scores provide an invaluable, comprehensive, and quantitative assessment of progress towards healthy and sustainable oceans. Such assessments are particularly valuable when repeated annually.
The OHI Global Fellows Program provides a cost-effective means to calculate global scores annually and trains graduate students to apply cutting-edge open data science tools.

The OHI Global Fellows Program is designed to fulfill our growing OHI assessment needs while providing opportunities for graduate students to learn cutting-edge data science skills. We piloted the program in 2018 and found it to be highly successful.

“These skills will be invaluable in my future work as an environmental data scientist.”
- Ellie Campbell, 2018 OHI Global Fellow

Not only will this program produce annual recalculated global scores, these highly trained graduate students will be adding benefit to the global OHI Community of Practice by helping to support government groups calculating OHI scores for their own nations.

More information: ohi-science.org/news/training-the-next-generation-of-ocean-data-scientists The Global Fellows program, in their own words: ohi-science.org/globalfellows


Steal text from Mel's, 1-pagers
link to their website, blogs,
Application material
