---
output:
 html_document:
   toc: true
   number_**section**s: true
bibliography: OHI_global_and_pressures.bib
# csl: ecology-letters.csl

---

<!-- NOTE to Mel from #737: I need to update how we did gdpppppc reference point -->

Artisanal fishing, often also called small-scale fishing, provides a critical source of food, nutrition, poverty alleviation and livelihood opportunities for many people around the world, in particular in developing nations [@allison_livelihoods_2001]. Artisanal fishing refers to fisheries involving households, cooperatives or small firms (as opposed to large, commercial companies) that use relatively small amounts of capital and energy and small fishing vessels (if any), make relatively short fishing trips, and use fish mainly for local consumption or trade. These traits differ from commercial scale fisheries that serve the global fish trade, and commercial and artisanal scale fisheries also differ in how they are valued by many communities around the world. Artisanal fisheries contribute over half of the world’s marine and inland fish catch, nearly all of which is used for direct human consumption [@**FAO**]. They employ over 90 percent of the world’s more than 35 million capture fishers and support another approximate 90 million people employed in jobs associated with fish processing, distribution and marketing [@**FAO**]. Artisanal fisheries also are distinguished by the role they play in shaping and sustaining human cultures around the world; this role contributes to their distinct value [@beier_ecosystem_2008]. For this reason, we designate artisanal fishing opportunities as a distinct public goal. In some countries like the U.S.A., artisanal fishing may happen under a commercial license (e.g. a family run lobster boat or individual shellfish harvesting permit), or under a recreational fishing permit (e.g. families fishing with rods for fish to eat); the food provided by these activities should ideally be captured under the food provision goal (**section** 6A), whereas the opportunity to pursue artisanal fishing is captured here. The goal is not about recreational fishing for sport, which is captured in food provision (if it provides food) and tourism and recreation (**section** 6G).

The livelihood and household economy provided by fishing are considered part of the Coastal Livelihoods and Economies goal below (**section** 6F), although similar to food provision from artisanal fishing it is currently impossible to measure on a global scale. Our focus is on the opportunity to conduct this kind of fishing. What is intended by the idea of ‘opportunity’ is the ability to conduct sustainable artisanal-scale fishing when the need is present, rather than the actual amount of catch or household revenue that is generated. Although this may seem nuanced on the value and intent of artisanal fishing, the opportunity to conduct this fishing is clearly of great importance to many people [@beier_ecosystem_2008]. Status for this goal is a function of need for artisanal fishing opportunities and whether or not the opportunity is permitted and/or encouraged institutionally and done sustainability. This need could potentially be driven by any number of socio-economic factors, but perhaps the simplest and most directly tied to this need is the percent of the population that is below the poverty level. Data on how many people live below the poverty level are not available for many countries. Therefore, we used an analogous proxy that is more complete globally: per capita gross domestic product (pcGDP) adjusted by the purchasing power parity (PPP). This metric translates the average annual income (pcGDP) into its local value (PPP). These data correlate with UN data on the percent of a population living below the $2/day international poverty standard (linear: R2 = 0.61, p <0.001; logarithmic regression: R2 = 0.76, p <0.001). Because the relationship is a better fit with the log-linear regression, we log-transform the PPPpcGDP scores before using them.

To assess the opportunity or ability to meet this demand, we used data from Mora et al. [-@mora_management_2009], which scores countries on the institutional measures that support or facilitate artisanal and small-scale fishing. The data come from Figure S4 in Mora et al. [-@mora_management_2009], which is based on two survey questions focused on recreational and artisanal fishing (see Table S5 below for questions) and are on a scale from 0 to 100 (which we then rescale 0-1), where higher scores indicate better management. We extracted the data from the color codes on the map in Figure S4. There may be some small errors far a few countries due to difficulty of distinguishing between the two red colors at the lowest end of the scale.

The sustainability of artisanal fishing practices could be approximated by the percent of fishermen that use sustainable gear such as hook and line versus unsustainable methods such as dynamite, cyanide and, arguably, gill net fishing. Unfortunately data on proportion of gear type used within a country is scarce at best and so we were unable to include this term in the calculation of this goal; we present it here for conceptual completeness.

Status for this goal (x<sub>AO</sub>) is therefore measured by unmet demand (D<sub>U</sub>), which includes measures of opportunity for artisanal fishing (O<sub>AO</sub>, defined below) and the sustainability of the methods used (S<sub>AO</sub>):

_x<sub>AO</sub> = (1 – D<sub>U</sub>) * S<sub>AO</sub>_, (**Eq. S22**)

where:

_D<sub>U</sub> = (1 – PPPpcGDP) * (1 – O<sub>AO</sub>)_, (**Eq. S23**)

PPPpcGDP is the log-transformed, rescaled purchasing power parity adjusted per capita GDP as described above, and O<sub>AO</sub> is the access to artisanal-scale fishing determined by Mora et al. [-@mora_management_2009]. We rescaled the log-transformed values from 0-1 under the assumption that very low values represent very high demand by nearly everyone in the country and should therefore make demand [1 – PPPpcGDP] approach 1.0. To rescale the values we used the minimum and maximum values across all countries in the most recent five years as the 0.0 and 1.0 values, respectively. In the future, if values exceed the current maximum PPPpcGDP, those countries will be assumed to have no demand for artisanal fishing and the value would be capped at 1.0. With this formulation, developed countries with lower demand for artisanal scale fishing (i.e. low poverty, or high PPPpcGDP) would score high, regardless of the opportunity made available (since it would not matter to many), and developing countries with high demand and opportunity would also score high. Because no data or information exist globally on the proportion of fishermen using sustainable versus unsustainable gear, S<sub>AO</sub> is set to 1 for all current calculations for all regions. The reference point for this goal is 1.0, i.e. all demand for artisanal fishing is allowed and/or achieved and done in a sustainable manner. To calculate the trend in this goal we used the annual change in the Status. Because we only have one value for O<sub>AO</sub>, the Trend becomes the change over time in the PPPpcGDP, i.e., how ‘unmet demand’ is changing over time.

We identified a subset of possible ecological pressures that affect the potential delivery of this goal, including chemical and nutrient pollution, alien species, subtidal and intertidal habitat destruction, commercial fishing, artisanal and small-scale low-bycatch and destructive fishing, and changes in sea surface temperature (SST). With these pressures we captured those factors that would affect the demand for artisanal fishing, the opportunity to practice artisanal fishing, or the sustainability of the practice. As such, pressures to the ecological system that would lead to changes in harvested fish populations can have a small potential impact on this goal by reducing stocks and therefore reducing the potential opportunity to catch fish. These ecological impacts have a lower weight than for the Food Provision goal, where the focus is on the amount of food produced. Social pressures, which will affect poverty levels, are included, as described in **section** 2.

Resilience was measured using measures of ecological integrity within coastal areas, the WGI, and regulations and other institutional measures pertaining to habitat resilience and fishing resilience (see Table S22 for list of data used). See general methodology above (**section** 2D) for details on how the layers were combined.

Several issues and datasets that are relevant to Artisanal Fishing Opportunities were not included in our calculations for a number of reasons. High unemployment can lead to a greater demand for artisanal fishing opportunities [@cinner_socioeconomic_2009], but unemployment is not a good measure of potential 'demand' for most developing countries since many people not working do not get recorded in unemployment statistics, even though it may be relevant for developed countries. Regardless, it is very difficult to set an arbitrary cut-off for developing versus developed countries, and so there is no clear way to use unemployment data for this goal.

Another potential driver of demand for artisanal fishing opportunities is local preference for seafood and/or access to other sources of protein. Previous analyses have shown that seafood consumption (a proxy for preference for seafood) does not correlate well with national-level artisanal catch statistics [@halpern_global_2008] and access to other sources of protein is difficult to measure, and so we did not use either of these measures here.

Finally, for our sustainability measure in the Status dimension we also considered using the information and data contained in Pitcher et al. [-@tony_pitcher_evaluations_2006] which looks at compliance of 53 countries with the UN’s Code of Conduct for responsible fisheries. These results are strongly correlated with the data from Fig. S4 in Mora et al. [-@mora_management_2009] (p < 0.001; R2 = 0.22), and thus we used the Mora et al.

**Table S5**. Questions from Mora et al. [-@mora_management_2009] that were used to evaluate access to artisanal scale fishing.

| If recreational fishing exists to any extent, which of the following apply?|If artisanal fishing exists to any extent, which ofthe following apply?|
|------|-------|
|- Are recreational fishermen required to havea  fishing license? Y/N  <br> - Are there regulations to the size of fishcaught? Y/N <br> - Are there regulations to the number of fishcaught? Y/N <br> - Are there regulations to the number offishermen allowed to fish? Y/N <br>- Are there statistics being collected for thissort of fishing? Y/N | - Are there regulations to the size of fishcaught? Y/N <br> - Are there regulations to the number of fishcaught? Y/N <br> - Are there regulations to the number offishermen allowed to fish? Y/N <br>- Are there statistics being collected for thissort of fishing? Y/N|                      
