---
output:
 html_document:
   toc: true
   number_**section**s: true
bibliography: OHI_global_and_pressures.bib
# csl: ecology-letters.csl

---

Ref: 42-47

The present-day pelagic ocean sink for anthropogenic carbon dioxide, estimated at approximately 2000 TgC y-1, accounts for about a quarter of total anthropogenic CO2 emissions to the atmosphere and helps mitigate a key driver of global climate change41. The physical-chemical mechanisms driving the ocean sink are well understood but are not directly amenable to human management. Deliberate carbon sequestration strategies via direct injection and biological fertilization have been proposed but are controversial42. Highly productive coastal wetland ecosystems (e.g., mangroves, salt marshes, seagrass beds) have substantially larger areal carbon burial rates than terrestrial forests, and so-called "Blue Carbon" has been suggested as an alternate, more manageable carbon sequestration approach43. The global carbon removal by these system is not well known, ranging in a recent estimate from 67- 215 TgC yr-1 (Ref. 44), though the fraction of this flux attributable as an anthropogenic rather than natural sink is poorly characterized. The rapid destruction of these coastal habitats may release large amounts of buried carbon back into the ocean-atmosphere system. Donato and colleagues45, for example, estimate that mangrove deforestation generates emissions of 20-120 TgC yr-1. Our focus here, therefore, is on coastal habitats because they are threatened, have large amounts of stored carbon that would rapidly be released with further habitat destruction, have the highest per-area sequestration rates of any habitat on the planet, and are amenable to management, conservation, and restoration efforts. We refer to this goal as Carbon Storage but intend its meaning to include sequestration.

We focused on three coastal habitats known to provide meaningful amounts of carbon storage: mangroves, seagrasses, and salt marshes46. For mangroves, we focused all forests, including coastal mangroves that are on land or in river deltas which provide significant additional amounts of carbon storage. As with other goals that rely on habitats for Status, we measured the Status of Carbon Storage (xCS) as a function of its current ‘condition’ (Cc) relative to a reference condition (Cr) and a variable that weights the relative contribution of each habitat type (k) to total carbon storage, measured as the amount of area each habitat covers (Ak) relative to the total area covered by all three habitats (AT) given the available data. See biodiversity goal (section 6J) for details on how habitat data were processed. Although Carbon sequestration rates and storage capacity can vary among the three habitats, value are similar enough across habitats and vary enough geographically within habitats47 that we assumed equal potential value for each. Thus, Status is:

 􀂦 􀂸 􀂸􀂹 􀂷 􀂨 􀂨􀂩 􀂧 􀀠 k T k r c CS A A C x C 1 * . (Eq. S28)

 We employed several different methods for calculating habitat condition scores depending on the habitat of interest and available data (see Table
S7).

We scaled each habitat’s area to At for two reasons. First, it avoids penalizing a country that naturally lacks one of the habitats (e.g., Canada is too cold to have mangroves). Second, it ensures that habitats influence the goal score proportionately to their area of extent. This rewards the protection of large extents of habitat but does not assign a higher weight to higher habitat diversity. As such, our measure underestimates the actual amount of carbon storage being done by these coastal habitats (because we cannot account for habitats we do not know exist). Reference area for each habitat is treated as a fixed value; in cases where current area might exceed this reference value (e.g., through restoration), we cap the score at the maximum value (1.0). Although this does not give credit for restoration efforts improving things, data tend to be of poor quality making it difficult to determine true increases, and in general habitat restoration beyond reference values is extremely unlikely.

The Trend for this goal is the slope of the change in Status, as per general methods in section 2B. Because of variable data availability and quality for each habitat, slightly different methods were used for each habitat (see Table S7). We identified a subset of possible pressures that affect the condition of the key protective habitats and therefore the potential delivery of this goal, including chemical and nutrient pollution, alien species, subtidal and intertidal habitat destruction, destructive artisanal fishing, and changes in sea surface temperature (SST), ocean acidification, and UV radiation (Table S22 and section 2C for details). Resilience was measured as the average of the regulatory measures (Reg) related to pollution mitigation and habitat protection, and the social integrity measures captured by the World Bank’s WGI. See general methodology above (section 2D) for details on how the layers were combined.

Ideally, we would assign different weights to the habitats based on their relative ability to store carbon, but exact values are currently poorly known. This model can incorporate such weights once they are available in a similar way to the methods developed for the Coastal Protection goal (see following section). 6E. Coastal Protection This goal aims to assess the amount of protection provided by marine and coastal habitats to coastal areas that people value, both inhabited (homes and other structures) and uninhabited (parks, special places, etc.). At local and regional scales data may exist on all these variables at a high enough resolution to map and calculate exactly which habitats are providing how much protection to which coastal areas. At global scales, such data do not exist and so we focused on EEZ-scale assessments, even though this scale does not allow one to account for the spatial configuration of habitats relative to coastal areas and human populations. Consequently, we assumed that all coastal areas have value (and equal value) and assessed the total area and condition of key habitats within each EEZ (without regard to their precise location relative to coastal areas). The habitats that provide protection to coastal areas for which we have global data include mangroves, coral reefs, seagrasses, salt marshes, and sea ice.


Table S7. Reference states for each habitat for which it is known and used in the Carbon Storage model.
Habitat Method for Calculating
Condition
Method for Calculating
Area
Data Used for
Calculating Trend
Seagrass Current % cover or hectares
of habitat divided by
reference % cover or hectares
Seagrass extent per oceanic
region (vector-based)
Calculated across data
from 1975 to 2010
Mangrove Current km2 divided by
reference hectares
Reference hectares Calculated across data
from 1980 to 2005
Salt
marsh
Increasing or stable trend
assigned condition = 1.0;
decreasing trend assigned
condition = 0.5
Salt marsh extent per
oceanic region
Categorical trend
assessments (increasing

2015:

Important changes were made to the goal model and the mangrove data layer. The model now incorporates coefficients (weights) to account for the amount of carbon that different habitats sequester, using new data from (Laffoley & Grimsditch 2009). For changes in habitat data, see details below in Biodiversity, Habitat subgoal.

Table S2. Weighting factors on relative carbon sequestration rates for habitats used in the carbon storage goal.

|Habitat Carbon storage| weight|
|---|---|
|Mangrove | 139|
|Saltmarsh| 210|
|Seagrass| 83|
