---
output:
 html_document:
   toc: true
   number_**section**s: true
bibliography: OHI_global_and_pressures.bib
# csl: ecology-letters.csl

---


People value marine waters that are free of pollution and debris for aesthetic and health reasons. Contamination of waters comes from oil spills, chemicals, eutrophication, algal blooms, disease pathogens (e.g., fecal coliform, viruses, and parasites from sewage outflow), floating trash, and mass kills of organisms due to pollution. People are sensitive to these phenomena occurring in areas that they access for recreation or other purposes as well as for simply knowing that clean waters exist. This goal scores highest when the contamination level is zero.

We condensed these various measures of pollution into four components that comprise the Clean Waters goal: eutrophication (nutrients), chemicals, pathogens and marine debris. This decision was meant to represent a comprehensive list of the contamination categories that are commonly considered in assessments of coastal clean waters [@borja_overview_2008] and for which we could obtain datasets. Because of limited data availability for chemical pollution, we measured the chemicals component as the average of land-based organic pollution, land-based inorganic pollution and ocean-based pollution from commercial shipping and ports. We did not have global data for oil spills and so could not include oil pollution, but in future assessments where such data exist it would be included in chemical pollution as well. In all four cases, the Status of these components is the inverse of their intensity (i.e., high input is a bad status).

We used the modeled input of land-based nitrogen input from Halpern et al. [-@halpern_global_2008] as a proxy for nutrient input. We did not use the Global NEWS data for river output of nutrients61 because it focuses on large watersheds that cover most of the global landscape but a small percentage of the global coastline. The modeled proxy approach does not allow the distinction between toxic and non-toxic bloom events that can arise from excess nutrient input (often both referred to in the literature as harmful algal blooms, or HABs) or at what nutrient concentration an ecosystem is pushed into a HAB condition (i.e., the threshold value). Local studies may be able to obtain information on such non-linear responses and include it as part of this Status measure.

The Status of chemical pollution was measured via three global datasets: land-based organic and inorganic pollution from agricultural pesticide use and runoff from impervious surfaces, respectively, and ocean-based pollution from commercial shipping and ports (all three from [@halpern_global_2008]). We were not able to assess specific toxic chemicals at the global scale; however regional case studies often will have data available for the quantities and toxicity of a range of chemicals put into watersheds and coastal waters.

Human-derived pathogens are found in coastal waters primarily from sewage discharge or direct human defecation. Since we did not have access to a global database of in situ measurements of pathogen levels, we used a proxy measure for the Status of pathogen pollution, namely the number of people in coastal areas without access to improved sanitation facilities. The underlying assumption is that locations with a low number of people with access to improved facilities will likely have higher levels of coastal water contamination from human pathogens. To estimate this pathogen intensity, we multiplied average population density within the 50km of land adjacent to coasts by the percentage of the population without access to improved sanitation. This allows countries with low coastal population densities and low access to improved sanitation to score better than high population countries with better access if the absolute number of people without access is lower in the small country.

The Status of trash pollution was estimated using globally-available coastal beach cleanup data from the Ocean Conservancy, which records the weight of trash per year that were collected. We normalized these data per length of coastline to create a tons/km of trash metric.

The Status of this goal (x<sub>CW</sub>) is then calculated as the geometric mean of the four components, such that:

$$
x_{CW} = \sqrt [ 4 ]{ a\ast u\ast l\ast d } (Eq. ??)
$$

where _a_ = the number of people without access to sanitation (i.e. coastal population density times % without access to enhanced sanitation) rescaled to the global maximum, _u_ = 1 – (nutrient input), _l_ = 1 – (chemical input), and _d_ = 1 – (marine debris input). The intensity or input values for each sub-component come from the data sources listed in Table S23. We used a geometric mean, as is commonly done for water quality indices62, because a very bad score for any one sub-component would pollute the waters sufficiently to make people feel the waters were ‘too dirty’ to enjoy for recreational or aesthetic purposes (e.g. a large oil spill trumps any other measure of pollution).

Although clean waters are relevant and important anywhere in the ocean, coastal waters drive this goal both because the problems of pollution are concentrated there and because people predominantly access and care about clean waters in coastal areas. We also have severe data limitations for open ocean areas with respect to measures of pollution. Finally, the high seas experience little meaningful regulation or governance over the input of pollution into these areas. We therefore calculate this goal only for the first 3nmi of ocean for each country’s EEZ. We chose 3nmi for several reasons, but found the status results to be insensitive to different distances (linear relationship between width of coastal area assessed and pollution stressor scores: R2 = 0.99, p<0.001; global average scores differed minimally, from 0.084 at 1km to 0.072 at 9km). First, for aspects of Clean Waters that relate to what people can see (i.e., people want to see clean waters), the marine ‘viewshed’ is the important variable. Second, it is the waters that are closest to shore that most affect people’s sense of Clean Waters, as it is these nearshore waters that affect their beach-going, shoreline fishing, and other activities.

Three of the four status measures did not have enough data to allow calculation of trends over the past 5 years, and so we used other related proxy measures to estimate trends. For both fertilizers and pesticides, FAO reports the tonnage used (by country) for most countries; these data were used to model the nutrient and organic chemical pollution components of Status and are therefore assumed to be correlated to trends that would emerge from rerunning the modeled watershed plumes calculated by Halpern et al. 3. Trends in trash were estimated using trends in coastal population density for the 50 miles closest to shore, based on the significant (albeit weak) relationship between the amount of trash found along beaches 63 and coastal population64 (log-log correlation; R2=0.13, p<0.001; n=99). We acknowledge that this approach to calculating the trend does not account for marine debris derived from ships and other ocean-based sources. Data for access to enhanced sanitation and coastal population density exist for multiple years and so we were able to calculate the trend directly for pathogen pollution. The Trend for the Clean Waters goal was then calculated as the average of these four trends.

Because we did not have an easy way to determine the reference point for these proxy data sets for trends, we convert the slopes into a -1.0 to 1.0 range by dividing the slope by the value for the initial year in the proxy data and by the number of years measured, i.e. treating the initial year as the reference point and calculating the annual percent change from that initial point until the more recent data year. We then follow the standard procedure described in the general methodology above (**section 2B**).

This goal is unique in that the maximum Status is also the absence of Pressures. As such, one minus the Status of each pollutant was used for Pressures data. Pressures were therefore the intensity and input of nutrients, chemicals, pathogens, and trash (as listed above). High population density and industrial intensity threatens to increase the level of human-derived contamination in the future (unless there is strong governance in place to contain the potential effects). All four pressures were weighted equally important (see **Table S25 - pressure matrix**)

For Resilience in the clean waters goal, we excluded measures of ecological resilience, as clean waters may occur also in the presence of a compromised food web which does not necessarily affect the ability of the system to stay uncontaminated. For measures of social structure and governance we used data from the Worldwide Governance Indicators (WGI) and CBD questions related to clean water (**Table S22 - data layers**).

A number of potential components of clean water were not included due to lack of global datasets, including toxic algal blooms, oil spills, turbidity (sediment input), and floating trash. In future applications of the Index where such data are available, they would be included in their appropriate component of Clean Waters (nutrients, chemicals, and trash, respectively).
