---
output:
 html_document:
   toc: true
   number_**section**s: true
bibliography: OHI_global_and_pressures.bib
# csl: ecology-letters.csl

---

The Status of the Habitat sub-goal (xHAB) was assessed for all habitats for which at least some global data were available, specifically: mangroves, coral reefs, seagrass beds, salt marshes, sea ice edge, and subtidal soft-bottom habitats. Status was assessed as the average of the condition estimates for each k habitat present in a region (Ck; measured as the loss of habitat and/or % degradation of remaining habitat), such that:

k C x k i k HAB 􀂦􀀠 􀀠 1 , (Eq. S40) where Ck = Cc/Cr and Cc is the current condition and Cr is the reference condition specific to each k habitat present in the region. This formulation ensures that each country is assessed only for those habitats that can exist, e.g. Canada is not assessed on the Status of its (nonexistent) coral reefs. We generally considered the reference years to be between 1980-1995 and the current years to be between 2001-2010, although these varied by habitat due to data availability.

A significant amount of pre-processing of the habitat data was needed to fill data gaps and resolve data quality issues (see the data layers section for details on data sources). Because consistent habitat monitoring data was unavailable for many countries, anomalous values can occur. This is particularly true for highly variable habitats like seagrasses or coral reefs which can have significant site-to-site and yearto- year differences in extent and condition 71,72. Biases may also have been introduced from spatial (e.g. protected or impacted sites) and temporal (e.g., directly after a disturbance event) selections in sampling. In regions where we had a limited number of surveys in a particular country, overall Status can be under- or overestimated because of these fluctuations.

Trend in habitat data were calculated as the linear trend in extent or condition with slight variations depending on habitat type. Coral reef habitat trends were calculated on a per country basis, using all available data. For seagrasses we calculated trends on a per site basis. For mangroves we used the rate of change in areal extent 73 over the entire time series of available data (1980-2005). For sea ice we calculated the slope across three-year moving averages to smooth out potential climate variation, with 2009 (average of 2008-2010) as the most recent year. For soft-bottom habitat we simply calculated the slope of the recent change in condition over the past five years, i.e. the change in proportion of catch from trawl fishing per unit area of habitat within a region.

Ecological pressures varied by habitat (see Table S22 for details) and were applied per-country depending on which habitats were present in each country. Social pressures were assumed to affect all habitats equally, based on the WGI index. Similarly, Resilience measures varied by habitat (see Table S22 for details), and therefore country, depending on which Pressures ranked most highly for each habitat. Ecological integrity was included in Resilience measures here, unlike other habitat-based goals, as it more directly relates to the intent of the goal (Biodiversity) than for other goals (Carbon Storage and Coastal Protection). We also included several Resilience measures from the CBD questionnaire that apply broadly to the goal of biodiversity conservation even though not tied to specific pressures (which is the criterion we use for all other Resilience measures). Social resilience was assumed to be equally relevant to all habitats and all countries and was based on the WGI index.

Data availability remains a major challenge for species and habitat assessments. We compiled and analyzed the best available data in both cases, but key gaps remain. Although several efforts have been made in recent years to create or compile the data necessary to look at the status and trends of marine habitats, most efforts are still hampered by limited geographical and temporal sampling, although mangroves are an exception74. The few habitats that are well-monitored cannot necessarily be easily extrapolated to draw conclusions about the global status and trends of habitats. In addition, most benthic habitats have only been monitored since the late 1970s at the earliest, many sites were only sampled over a short period of time, and very few sites were monitored before the late 1990s so establishing reference points was difficult. Salt marshes and seagrasses were the most data-limited of the habitats included in the analysis. Similar issues existed for the Species sub-goal. Although several marine habitat-forming species, and some commercially important groups (e.g., tuna and billfishes) were included, the majority of marine species have not yet been formally assessed by the IUCN. Taxonomic and geographical biases may have affected our ability to detect changes, especially at smaller spatial scales. In addition, the IUCN assessments represent the extinction risk primarily at a species level. For those species with broad spatial distribution and/or that comprise several populations, these estimates may not be representative of regional or local extinction risks.
