---
output:
 html_document:
   toc: true
   number_**section**s: true
bibliography: OHI_global_and_pressures.bib
# csl: ecology-letters.csl

---

The ‘Lasting Special Places’ sub-goal focuses instead on those geographic locations that hold particular value for aesthetic, spiritual, cultural, recreational or existence reasons [@trc_inventory_2004]. This sub-goal is particularly hard to quantify. Ideally one would survey every community around the world to determine the top list of special places, and then assess how those locations are faring relative to a desired state (e.g., protected or well managed). The reality is that such lists do not exist. Instead, we assume areas that are protected represent these special places (i.e. the effort to protect them suggests they are important places). Clearly this is an imperfect assumption but in many cases it will be true.

Using lists of protected areas as the catalogue of special places then creates the problem of determining a reference condition. We do not know how many special places have yet to be protected, and so we end up having all identified special places also being protected. To solve this problem we make two important assumptions. First, we assume that all countries have roughly the same percentage of their coastal waters and coastline that qualify as lasting special places. In other words, they all have the same reference target (as a percentage of the total area). Second, we assume that the target reference level is 30% of area protected [@hughes_climate_2003].

As such, we calculate the Status of this goal as:

$$
x_{LSP} = \frac { \left( \frac{\%_{CMPA}}{\%_{Ref_{CMPA}}} + \frac {\%_{CP}}{\%_{Ref_{CP}}} \right) }{ 2 } \quad \quad (Eq.\quad S37)
$$

where $\%_{CMPA}$ = proportion of coastal marine protected area, $\%_{CP}$ = proportion of coastline protected, and $\%_{Ref}$ = 30% for both measures. 
We focus only on coastal waters (within 3 nautical miles of shore) for marine special places because it was assumed that lasting special places are primarily in coastal areas; we wanted our estimates of % area protected to be bounded to this coastal region. 
For coastlines, we focused only on the first 1-km-wide strip of land as a way to increase the likelihood that the area being protected by terrestrial parks is connected to the marine system in some way. We found that the coastal (terrestrial) protected area extent scales linearly from 1 to 9 km inland (R^2^ = 0.98), such that our decision to use a 1 km^2^ buffer should not affect results at all. 
We use the compiled list of protected areas provided by the United Nation’s World Database on Protected Areas (WDPA) to derive these % protected values [@unep-wcmc_world_2015]. The WDPA aggregates several key databases: IUCN’s World Commission on Protected Areas, Global Marine Protected Areas, UNESCO World Heritage Marine sites, National Parks and Nature Reserves, and the United Nations List of Protected Places.

In most of these cases the year of designation is listed for each protected area, and so we use the annual increase in % area (or % coastline), relative to the reference point, across the five most recent years (2011-2015) to derive the trend in protected sites, and therefore the Trend in Status of Lasting Special Places. Pressures to this goal derive primarily from pollution and habitat destruction (see **Table S22**). Resilience measures for this goal come from CBD questions relating to pollution and habitat destruction, the amount of money (proportional to GDP) invested into protected areas, and the WGI indicators.
