---
output:
 html_document:
   toc: true
   number_**section**s: true
bibliography: OHI_global_and_pressures.bib
# csl: ecology-letters.csl

---

In many countries the harvest of non-food natural products is important for local economies and can also be traded internationally. The sustainable harvest of these products is therefore an important component of a healthy ocean. This goal assesses the ability of countries to maximize the sustainable harvest of living marine resources, such as corals, shells, seaweeds, and fish for the aquarium trade. It does not include bioprospecting which focuses on potential (and largely unknowable and potentially infinite) value rather than current realized value, or non-living products such as oil and gas or mining products which by definition are not sustainable.

We had access to export data for six different natural products (see Table S22) and so calculate an individual Index score for each of them: coral, ornamental fish, fish oil, seaweeds and marine plants, shells, and sponges. We did not have data for other key natural products such as wood from mangroves, and we excluded oils from mammals as they are widely seen as (currently) unsustainably harvested due to low mammal populations. Mammal oils represented a small (< 2%) and decreasing  amount of total oil harvest each year (since 1993 it has been well below 1%), although for some countries it remains a significant percent of total oil harvested. We calculated the goal score with and without coral harvest because many feel that all coral harvest is unsustainable. Unsustainable harvest of natural products is included in our sustainability measure (see below). We focus on results with coral products included, and note that overall goal scores with and without corals included were nearly identical for all countries (linear regression, p < 0.001, R2 = 0.95; average per-country difference = -0.016; slope = 1.03 indicating that scores are slightly higher with corals included). Countries with goal scores much higher (> 0.10) with corals included were Nicaragua, Fiji, El Salvador, and Mauritius and much lower (< -0.10) with corals included were Somalia, Senegal, Vanuatu, Marshall Islands, Bangladesh, Dominican Republic, Madagascar, Bosnia and Herzegovina, Guinea, Taiwan, Italy, Belize, and USA.

For the Status of each product, we assessed the most recent harvest rate (in metric tons) per country relative to the maximum value (in 2008 USD) ever achieved in that country, under the assumption that the maximum achieved at any point in time was likely the maximum possible. This creates a reference point internal to each country. We then established a buffer around this peak catch because we do not know whether it is sustainable (similar to what was done for the fisheries sub-goal of food provision, Section 6A1). Any value within 35% of the peak was set to 1.0, with values below that rescaled to this 35% buffer value. We chose a 35% buffer following the logic of the wild-caught fisheries sub-goal, where a 25% buffer is used around mMSY. Because mMSY for wild-caught fisheries is already 10% below peak landings, we added 10% to the Natural Products buffer as a coarse approximation of the buffer mMSY builds around peak landings.

For countries that never harvested a product, we assumed they cannot produce it (in general because the product does not exist there) and so treat that as a ‘no data’ rather than a zero value. For countries that harvested a product at any point in time, empty values are treated as zeros since the country clearly has the capacity to harvest that product. We then rescaled these values from 0-1, with any value within 35% of the peak harvest set to 1.0, and adjusted these harvest scores by estimates of the sustainability of the harvest rate. Although we do not know actual sustainability levels, we accounted for this factor by adjusting the harvest level by a sustainability term for each product that is based on the log-transformed intensity of harvest per km2 of coral and/or rocky reef, depending on the product, relative to the global maximum (its ‘exposure’), and for ornamental fish and corals also the ‘risk’ that is associated with known unsustainable harvest practices (i.e., the intensity of cyanide fishing for ornamental fish, and any harvest of corals since they are CITES protected species). We logtransformed the harvest intensity scores because of a highly skewed distribution of per-country values; because we do not know the true threshold of sustainable harvest, nearly all values would be considered highly sustainable without the logtransformation. Finally, for fish oil, exposure was calculated based on stock status assessments. For each country we calculated the weighted proportion of species harvested sustainably. We assigned each species an exploitation status based on its catch each year relative to its MSY over the span of the database, 1950-2006, following the definitions in Table S6 which are based on FAO definitions plus the ‘rebuilding’ category developed by the Sea Around Us Project {@kristin_kleisner_marine_2011}. When insufficient information exist to assign a stock status, the stock was excluded from analyses. The sustainability index is computed for each t year as:
􀂦 􀂦 􀀠 􀀠 􀀠 5 1 5 1 , * k k k kk NP t N wN S , (Eq. S24)
where N is the number of species in each k category of exploitation and w is the weight assigned to each category of exploitation status (Table S6).

The Status of each natural product p (x<sub>NPp</sub>) is therefore: x<sub>NPp</sub> = Hp * Sp , (Eq. S25) where Hp is the harvest level for a product relative to its own (buffered) peak reference point, Sp is the sustainability of that harvest, with: v p N RES 􀀎 􀀐􀀠 1 , (Eq. S26) where E is the exposure term, R is the risk term and is set to 1.0 for corals and to the relative intensity of cyanide fishing for ornamental fish, and Nv = 1 or 2 depending on whether or not a viability term is used.

Using Eq. S25 above we calculated the Status score for each product for the previous five years, and then used the slope of these Status scores to calculate the Trend for each product. For Pressures, we treated each product separately because different pressures affect each of the products differently, and therefore we calculate a unique Pressures score for each product (see Table S25 for stressors used for each product and the relative weights applied). We also calculated unique Resilience scores for each product since the regulation (Reg) Resilience measures are connected to specific stressors (see section 2D above). As such, we were able to calculate a total Index score for each product.

To create a single score for the Natural Products goal (xNP) we then took the weighted average of the individual product scores, such that:

x
N
p
pp
NP
􀂦􀀠
􀀠 1 , (Eq. S27)

where N is the number of products that have ever been harvested and wp is the proportional peak dollar value of each product relative to the total peak dollar value of all products (in 2008USD). If a product had a peak value, but was missing a harvest value for that product in a given year, then we used wp = 0 during the aggregation for that year. Note that for the Trend calculation, some regions have staggered years between products for the slope calculations (2003-2007 for Corals, Ornamental Fish, and Shells and 2004-2008 for the rest).

There are several important caveats about the approach we used to assess the Status of natural product harvest. First, our approach is supply (export) based. If declining demand for a natural product causes a decline in production, the producing country’s score declines even if it could (sustainably) produce more. Similarly, if a country chose to reduce or halt production of a natural product in order to improve conservation or sustainability, its score might still decline, although this decline might be buffered by improvement in the Resilience dimension. Additionally, such decline would likely be compensated by increased scores in several other goals resulting from decreased harvest pressures. Second, we do not have MSY estimates for any of the six natural products evaluated. When such estimates become available in the future they can easily be incorporated here, as is done in the wildcaught Fisheries sub-goal of the Food Provision goal. These caveats may lead to decreases in the score for a country despite maintenance or even improvement of the sustainable harvest of natural products; we instituted the 35% buffer around peak harvest (described above) as a way to help mitigate these potential issues. Finally, our estimate of the sustainability of many of the harvest practices is likely overly optimistic. For example, fishing for ornamental trade often employs unsustainable techniques such as cyanide fishing, but we have few data to inform such an estimate of sustainability in the Status calculation for ornamental fish.


**Table ????. Definitions and weights assigned for each category of exploitation status**

|Exploitation Status| w | Definition |
|---|---|---|
|Developing | 1.0 | Stock landings have not reached a peak or peak occurs in the last year of the time series|
|Fully exploited | 1.0 | Stock landings are between 50-100% of peak |
|Overexploited | 0.5 | Stock landings are between 10-50% of peak |
|Collapsed | 0.0 | Stock landings are <10% of peak & recent trend is <0 |
|Rebuilding | 0.25 | Stock landings are between 10-50% of peak & recent trend is >0 |

2015:

The sustainability component for fish oil was changed. All other products were calculated as before, except for improvements in data gap-filling as described here and in section 6 below. Updates in data used for this goal are detailed below in Section 5, but we note here that past years’ data were revised by FAO and so some changes are due to updated data.

This goal model calculates overall status by weighting the status of sustainable harvest of each product (tonnes) by its proportional value (US dollars) relative to other harvested products. Because of inconsistencies with how data are reported to FAO on the harvest and monetary value of each product (many countries report only one or the other of the two measures in a given year), there are many cases where harvest data but no value data are reported, and equal numbers of cases with value data but no harvest data. These mismatches in reporting would cause products to ‘drop out’ of the calculation of overall status, thus losing real data. Because a reported US dollar value must come from 16 the harvesting of a product, and similarly the reporting of harvested tonnage implies some economic value of that product, we developed several methods to fill these gaps.

To address this and other issues related to inadequate data reporting, we used a correlative model to estimate missing tonnes or US dollar values, assuming that the relationship was linear. This was done after smoothing harvest data (both tonnes and US dollars) with a 4-year moving window (skipping missing values rather than treating them as 0) to help fill gaps and minimize the potential effect of under- or over-reporting of annual harvest. This process required a minimum of 4 years of data from both data layers. We also had to gap fill a few of the sustainability scores for products when yield was reported but no habitat existed in the region with which to calculate exposure (see Halpern et al. 2012). In these cases we used the regional average across all other regions with sustainability scores (ornamentals: 2013 filled value=0.946, 2012 filled value=0.942, N=28; corals: 2013=0.389, 2012=0.383, N=28; sponges: 2013=0.974, 2012= 0.974, N=22; shells: 2013=0.916, 2012= 0.911, N=19; seaweeds: 2013=0.817, 2012=0.823, N=28).

To determine the relative contribution of each product to the overall status of the goal, we used the ratio of the maximum US dollar value for a product (from the smoothed, gap-filled data) across all years of data for the product, relative to the sum of maximum values for all products harvested in the country.
