---
title: "Exploring scores"
output: html_document
---

A place to explore scores.


```{r setup, include=FALSE}

library(here)
library(tidyverse)

```


## trends in TR

```{r tr declines}

trends <- read.csv(here("yearly_results/global2019/Results/data/trends_2019.csv"))
regions <- read.csv("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2019/gh-pages/globalprep/spatial/v2017/output/georegion_labels.csv") %>%
  rename(region_id = rgn_id) %>%
  select(-r0_label)

filter(regions, r2_label == "Northern America")

trends <- left_join(trends, regions, by='region_id')

tr <- trends %>%
  select(country, region_id, TR, r1_label, r2_label) %>%
  group_by(r2_label) %>%
  summarize(TR = mean(TR, na.rm=TRUE)) %>%
  arrange(TR)
data.frame(tr)

```


## trends in FIS

```{r}

left_join(trends, regions, by='region_id') %>%
  arrange(FIS)

filter(trends, r2_label == "Northern America")

fis <- trends %>%
  select(country, region_id, FIS, r1_label, r2_label) %>%
  group_by(r2_label) %>%
  summarize(FIS = mean(FIS, na.rm=TRUE)) %>%
  arrange(FIS)
data.frame(fis)

```


## mariculture

```{r}

scores <- read.csv(here("yearly_results/global2019/Results/data/scores_eez2019.csv"))

scores <- left_join(scores, regions, by='region_id')

arrange(scores, Index)


filter(trends, r2_label == "Northern America")

fis <- trends %>%
  select(country, region_id, FIS, r1_label, r2_label) %>%
  group_by(r2_label) %>%
  summarize(FIS = mean(FIS, na.rm=TRUE)) %>%
  arrange(FIS)
data.frame(fis)

```


## scores

```{r}

scores <- read.csv(here("yearly_results/global2019/Results/data/scores_eez2019.csv"))

arrange(scores, -MAR)


filter(trends, r2_label == "Northern America")

fis <- trends %>%
  select(country, region_id, FIS, r1_label, r2_label) %>%
  group_by(r2_label) %>%
  summarize(FIS = mean(FIS, na.rm=TRUE)) %>%
  arrange(FIS)
data.frame(fis)

```
