See hab_extent layer for more information.

#### Coral 
Trend was calculated using condition data from 1975-2006.  Condition data was estimated as percent live coral cover based on 12,634 surveys from 1975-2006 (Bruno and Selig 2007, Schutte et al. 2010). When multiple data points are available for the same site and year, we average these data, and also average the site data to calculate a per country per year average. However, data were missing for several countries and some countries did not have data for the reference or current year time periods or had only 1-2 surveys. Because coral cover can be highly temporally and spatially dynamic, having only a few surveys that may have been motivated by different reasons (i.e., documenting a pristine or an impacted habitat) can bias results. To calculate Ck we used fitted values from a linear trend of all data per country, which was more robust to data poor situations and allowed us to take advantage of period of intense sampling that did not always include both current and reference years. Then, we create a fitted linear model of all these data points in 1975-2010, provided that 2 or more points are in 1980-1995 and 2 or more points are in 2000-2010. Where country data were not available, we used an average from adjacent EEZs weighted by habitat area, or a georegional average weighted by habitat area, based on countries within the same ocean basin.

#### Mangroves 
We used Hamilton and Casey's (2014) mangrove cover data to estimate the proportional yearly change in mangrove area using a linear regression model of the most recent five years of data (i.e., slope divided by data from the earliest year included in the regression model).  The slope was then multiplied by five to get the predicted change in 5 years.  The orgiginal mangrove data are provided yearly (2000-2012) at 30m raster cell resolution (with the estimated area of mangrove cover in each cell). 

#### Salt marsh 
Annual change rates in habitat area were calculated from 1994-2007, where available, using data from multiple sources (Bridgham et al. 2006, Dahl 2000, Ministry for the Environment 2007, JNCC 2004, EEA 2008). For Trend estimates, we extracted categorical condition data (‘increasing”, “stable”, “declining” score as 0.5, 0.0, and -0.5, respectively) from these sources on a per country basis for countries where both a current and reference data year available.

#### Sea ice 
Sea ice trend was calculated using sea ice concentrations from the USA National Snow and Ice Data Center (Cavalieri et al. 2014; https://nsidc.org/cryosphere/quickfacts/seaice.html).  The average yearly proportional change in extent was estimated with a linear regression model that included the most recent five years of data (e.g., slope estimate was divided by the extent for earliest year included in the regression model), and this value was multiplied by five to get the predicted change in 5 years.  Each year of data is a 3-year average, to smooth yearly variation, for the sea-ice habitats.    

#### Seagrass 
For trend in seagrass status we use two data sources (Waycott et al. 2009, Short et al. 2010). Short et
al. (2010) measured percent cover on a per sample, per site, per year basis, whereas Waycott et al.(2009) measured habitat area on a per site, per year basis. We used data from Short if there were at least 3 data points between 2001-2010. If this condition was not met, we calculated trends from Waycott for the most recent 10 years after 1990 or else we used the mean of the trend in the adjacent regions or the regions within the corresponding seagrass geographical regions using the same methods described above for the in status.

#### Soft-bottom subtidal 
Trend was estimated using the condition data (see hab_health). The average yearly change in condition was estimated with a linear regression model that included the most recent five years of data (e.g., slope estimate was divided by the extent for earliest year included in the regression model and then multiplied by five to get the 5 year estimate).   


