This layer includes yearly data for jobs in commercial fishing, mariculture, marine mammal watching, marine renewable energy, and, tourism. The data sources and methods for each sector are described below.

#### Commercial fishing
Data come from the United Nations Food and Agriculture Organization (FAO) Fisheries and Aquaculture Department which provides a Global Number of Fishers (GNF) (http://www.fao.org/fishery/statistics/global-fishers/en.) The data contains yearly total numbers of employees in commercial fishing, subsistence fishing, and aquaculture (land- and ocean-based combined) in more than 160 countries. The dataset includes the following occupational categories: aquatic-life cultivation, inland waters fishing, marine coastal waters fishing, marine deepsea waters fishing, subsistence and unspecified. We omitted jobs with an unspecified category to avoid overestimating employment for marine fishing or aquaculture. We omitted jobs in the subsistence category since subsistence opportunities are captured by the artisanal fishing opportunity goal of the OHI and in the aquatic-life cultivation category since that represents a distinct sector (see mariculture below). For commercial fishing, we eliminated inland waters fishing and summed marine coastal waters and marine deep-sea waters fishing for each country in each year. Data are reported separately for men and women, but we summed these numbers. Employment is disaggregated into full-time, parttime, occasional, and unspecified statuses. These categories are defined as full time workers having > 90% of their time or livelihood from fishing/aquaculture, part time workers are between 30-90% time (or 30-90% of their livelihood) and occasional workers are < 30% time. Unspecified status workers could fall anywhere from 0-100% time. Taking the midpoints of those ranges, we assume that 1 part time worker = 0.6 full time workers, 1 occasional worker = 0.15 full time workers, and 1 unspecified worker = 0.5 full time workers, which we used as a weighting scheme for determining total numbers of jobs.  The data also contain significant gaps, but they provide the most comprehensive source of global data on commercial fishing and aquaculture employment.

#### Mariculture
We used the FAO GNF dataset (see Marine jobs: commercial fishing above for full dataset description) to estimate jobs for mariculture. For this sector, we used data in the aquatic-life cultivation category. Again, employment is disaggregated into full-time, part-time, occasional, and unspecified statuses and we implement a weighting scheme where full time = 1 job, part-time = 0.6, occasional = 0.15, and unspecified = 0.5. Aquatic-life cultivation includes marine, brackish and freshwater aquaculture. In order to estimate the proportion of total aquaculture jobs that can be attributed to marine and brackish aquaculture, we used country-specific proportions of marine and brackish aquaculture revenues (compared to total revenues) calculated from FAO aquaculture production data (obtained from FishStat), assuming that numbers of jobs approximately scale with production in terms of revenue. For country-years where there were no data for the proportion of marine/brackish production because of gaps in the FAO production data, we used the proportion from the most recent year for which data were available. For countries for which we did not have proportion estimates from any years, we used the average proportion from the country’s geographic region (e.g., Caribbean, Polynesia, Eastern Asia), with the exception of American Samoa, for which we used the proportion value from Guam.

#### Marine mammal watching
The International Fund for Animal Welfare’s (IFAW) Whale Division provides time series data on whale watching in more than 115 coastal countries (O'Connor et al 2009). This dataset may be an imperfect representation of all marine mammal watching due to its focus on whales, although it does include data for other types of marine mammal watching (e.g., dolphins). However, to our knowledge, it is the most complete dataset pertaining to the global marine mammal watching industry. We obtained regional averages of the number of whale watchers per employee, as well as the number of whale watchers in each country. Using this information, we estimated the number of whale watching jobs in each country by dividing the country’s total number of whale watchers by the average number of whale watchers per employee for that country’s region (e.g., Africa & Middle East, Europe, North America). It is important to note that data are not annual, but there are at least four years of data for each country.
When IFAW reported “minimal” numbers of whale watchers, we converted this description to a 0 for lack of additional information. Because some of the whale watching in O’Connor et al. focused on freshwater cetacean viewing, we categorized the target species listed for each country as freshwater or marine. For countries with both marine and freshwater species, we categorized the whale watching in those countries as either 50% or 90% marine, based on the number of marine versus freshwater target species and information provided in the report narrative. For Colombia and Indonesia, more detailed information in the report narrative allowed for a more precise determination of the percentage of marine-based whale watching. We applied these marine proportions to data on the number of whale watchers before converting these estimates into employment estimates.

#### Marine renewable energy
For the two countries, France and Canada, which produce significant enough amounts of tidal energy to register with the UN Energy Statistics Database we estimated numbers of employees. For the La Rance plant in France, this information was obtained from a recent press statement (EDF 2011); we assumed employment stayed constant over the time period for which we had production data for this plant, given relatively consistent or even growing production. For the Annopolis Royal plant in Canada, we received information from the plant about employment over time (Ruth Thorbourne, personal communication, Aug 9 2011).

A note on marine renewable energy, which is an expanding industry with many positive and negative effects on humans and ecosystems beyond the actual energy harnessed (Lam & Roy 2014). Marine renewable energy includes five major technologies: tidal barrages, marine currents, waves, ocean thermal converters and salinity gradients. In global-scale Index assessments, marine renewable energy includes data only for the largest tidal barrage plants, as these data are available. These data are represented only as marine revenue and marine jobs at two plants capturing tidal energy: La Rance Tidal Power Station (France) and Annapolis Royal Generating Station (Canada). These two plants have large enough energy production to be included in the United Nations Energy Statistics database (http://data.un.org/Data.aspx?d=EDATA&f=cmID%3aEO) and have multiple years of data (Sihwa Lake Tidal Power Station in South Korea, the world's largest tidal power station only became operational in 2011 and could not be included for this reason). Marine renewable energy can also act as pressures and resilience on other goals within OHI; the details of these tradeoffs are very site-specific and best incorporated at regional assessment scales (e.g. Elfes et al. 2014) where information may be available on interactions over time.

#### Tourism
The World Travel & Tourism Council (WTTC) provides data on travel and tourism’s total contribution to employment for 180 countries (http://www.wttc.org/eng/Tourism_Research/Economic_Data_Search_Tool/). Although other global data sources on tourism are available (i.e., United Nations World Tourism Organization [UNTWO]), the WTTC database was chosen because it offers yearly time series data that span through the current year, it includes nearly complete coverage of all nations, and it disaggregates direct and total (direct plus indirect) employment impacts of tourism. WTTC provides projected data, however, we do not use these values. We used total employment data to avoid the use of literature derived multiplier effects. The WTTC shares a significant drawback with UNTWO data, in that data on coastal/marine and inland tourism are lumped. Therefore, a country-specific coefficient must be applied to estimate the jobs provided by coastal/marine tourism alone. We adjusted national tourism data by the proportion of a country’s population that lives within a 25 mile inland coastal zone.