The total tonnes of six natural product commodities (corals, ornamental fish, shells, fish oil, seaweeds and plants, and sponges) were determined for each region using export data from the FAO Global Commodities database. For each group the sum of the subcategories was calculated.  For ornamental fish we excluded the subcategory ‘Fish for culture including ova, fingerlings, etc.’ because it is not specific to ornamental fish and the subcategory ‘Ornamental freshwater fish’ because it is not from marine systems. Corals and shells are reported together in nine subcategories; we used the subcategories most closely tied to each, leading to the sum of two subcategories for corals and seven subcategories for shells (one subcategory was used for both). We did not use one subcategory – ‘Powder and waste of shells’ – as it likely a byproduct of the other subcategories rather than a primary target (and it comprises a very small amount of the total anyway).

If a country was missing tonnes or dollar values (but had one of the values), the missing data were estimated. FAO provides yearly data for the tonnes and dollar value generated for each natural product, however, countries often provide only one of these variables (and the data provided varies across years). To estimate these missing data, we used country-specific linear models to predict tonnes based on the dollar value of a product (or, vice versa). For the countries that did not have enough data to develop an adequate model, our models included the data for all the countries within a georegion. When there wasn’t enough data at the georegion scale, we used all the global data to predict missing values.  

```{r}
# data <- read.csv('../../../../ohiprep/globalprep/np/v2016/raw/commodities2products.csv') %>%
#   group_by(product) %>%
#   summarize(subcategory = paste(commodity, collapse = ", ")) %>%
#   select(commodity = product, subcategory)
# 
# kable(data)

```
