---
title: "SPP explore"
author: "Gage Clawson"
date: "10/29/2021"
output: html_document
---

## Explore the HAB data after new data updates

```{r setup, include=FALSE, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)

library(tidyverse)
library(here)
source('http://ohi-science.org/ohiprep_v2021/workflow/R/common.R')
```

```{r}
scores <- read_csv(file.path(here(), "yearly_results/global2021/OHI_final_formatted_scores_2021-11-04.csv"))


hab_scores <- scores %>%
  filter(goal == "HAB", dimension == "score", region_id != 0) 
  

## get top ten and bottom ten scores for 2021

DT::datatable(hab_scores %>%
  filter(scenario == 2021) %>%
  arrange(-value) %>%
    dplyr::select(goal, dimension, region_name, scenario, value))


reds <-  colorRampPalette(c("#A50026", "#D73027", "#F46D43", "#FDAE61", "#FEE090"), space="Lab")(65)
blues <-  colorRampPalette(c("#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4", "#313695"))(35)
myPalette <-   c(reds, blues)
```

Look at the sea ice layer for iceland

```{r}

trend <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/hab_seaice/v2021/output/hab_ice_trend_eez.csv')

trend_ice <- trend %>%
  filter(rgn_id == 143)

mean(trend_ice$trend) # -0.2295722

# Pretty obvious negative trend for Iceland seaice: -0.2295722

## look at health

health <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/hab_seaice/v2021/output/hab_ice_health_eez.csv')

health_ice <- health %>%
  filter(rgn_id == 143)
```

Look at the nutrient layer

```{r}



```



