---
title: "SPP explore"
author: "Gage Clawson"
date: "10/29/2021"
output: html_document
---

## Explore the SPP data after new data updates

```{r setup, include=FALSE, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)

library(tidyverse)
library(here)
source('http://ohi-science.org/ohiprep_v2021/workflow/R/common.R')
```

```{r}
scores <- read_csv(file.path(here(), "yearly_results/global2021/OHI_final_formatted_scores_2021-11-04.csv"))


ico_status <- scores %>%
  filter(goal == "ICO", dimension == "status", region_id != 0) 
  

## get top ten and bottom ten scores for 2021

DT::datatable(ico_status %>%
  filter(scenario == 2021) %>%
  arrange(-value) %>%
    dplyr::select(goal, dimension, region_name, scenario, value))


reds <-  colorRampPalette(c("#A50026", "#D73027", "#F46D43", "#FDAE61", "#FEE090"), space="Lab")(65)
blues <-  colorRampPalette(c("#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4", "#313695"))(35)
myPalette <-   c(reds, blues)
```


Qatar: 


```{r}
data <- scores %>%
  filter(dimension == "score") %>%   # focus only on score data
  filter(region_id != 213)  %>% # eliminate Antarctica
  mutate(value = round(value, 0)) %>%
  mutate(region_name = as.character(region_name)) %>%
  group_by(region_id) %>% 
  mutate(meanIndex=mean(value[goal=="Index"])) %>%
  ungroup() %>%
  data.frame() %>%
  filter(goal == "ICO")
  


data_qat <- data %>%
  filter(region_name == "Qatar")

data_qat


ggplot(data_qat, aes(y=region_name, x=scenario, fill=value)) + 
  geom_tile() +
  facet_grid(~goal) + 
  scale_fill_gradientn(colours=myPalette, na.value="black") +
  theme(axis.text.x  = element_text(angle=90, vjust=0.5), axis.text.y=element_text(size=10)) +
  ylab("") + 
  xlab("")


## Take a look at what species declined in Qatar

ico_spp_rgn_prepped <- read_csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/ico/v2021/int/ico_spp_rgn_prepped.csv',
                                col_types = "ddcccccdcccldcc") %>% 
  mutate(year = 2021)

# Read in ico_spp_countries from v2020
ico_spp_rgn_prepped_v2020 <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/ico/v2020/int/ico_spp_rgn_prepped.csv') %>%
  mutate(year = 2020)



qatar1 <- ico_spp_rgn_prepped_v2020 %>% 
  filter(rgn_name == "Qatar") %>% 
  dplyr::select(iucn_sid, presence, rgn_id, rgn_name, comname, sciname, cat, year)

qatar2 <- ico_spp_rgn_prepped %>% 
  filter(rgn_name == "Qatar") %>% 
  dplyr::select(iucn_sid, presence, rgn_id, rgn_name, comname, sciname, cat, year)

qatar <- rbind(qatar1, qatar2)


setdiff(unique(qatar2$comname), unique(qatar1$comname))

# [1] "Great White Shark"   "Gray reef shark"     "Blacktip reef shark" "Whitetip reef shark" "Green Turtle"       
 # 5 new species assessed here, all vulnerable or endangered
# 

```
```
