---
title: "SPP explore"
author: "Gage Clawson"
date: "10/29/2021"
output: html_document
---

## Explore the SPP data after new data updates

```{r setup, include=FALSE, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)

library(tidyverse)
library(here)
library(knitr)
source('http://ohi-science.org/ohiprep_v2021/workflow/R/common.R')
```

## Summarize IUCN status data

Calculate what percentage of animals fall under each risk category (LC, DD, NT, V, E, CE)

```{r}
data <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/spp/v2021/_data/iucn_risk_current_2020-3.csv')

data_grouped_2020_3 <- data %>%
  group_by(cat) %>% 
  summarise(count_spp = n()) %>%
  ungroup() %>%
  filter(cat != "DD") %>%
   mutate(total_spp = sum(count_spp)) %>%
  mutate(percent = (count_spp/total_spp)*100)

kable(data_grouped_2020_3)
sum(data_grouped_2020_3$count_spp) # 12792

# |cat | count_spp| total_spp|    percent|
# |:---|---------:|---------:|----------:|
# |CR  |       218|     12792|  1.7041901|
# |EN  |       376|     12792|  2.9393371|
# |EX  |        25|     12792|  0.1954346|
# |LC  |     10788|     12792| 84.3339587|
# |NT  |       566|     12792|  4.4246404|
# |VU  |       819|     12792|  6.4024390|


data <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/spp/v2021/_data/iucn_risk_current_2020-1.csv')

data_grouped_2020_1 <- data %>%
  group_by(cat) %>% 
  summarise(count_spp = n()) %>%
  ungroup() %>%
  filter(cat != "DD") %>%
  mutate(total_spp = sum(count_spp)) %>%
  mutate(percent = (count_spp/total_spp)*100)

kable(data_grouped_2020_1)

# 12283


data <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/spp/v2020/_data/iucn_risk_current_2019-1.csv')

data_grouped_2019_1 <- data %>%
  group_by(cat) %>% 
  summarise(count_spp = n()) %>%
  ungroup() %>%
  filter(cat != "DD") %>%
  mutate(total_spp = sum(count_spp)) %>%
  mutate(percent = (count_spp/total_spp)*100)

kable(data_grouped_2019_1)

# |cat | count_spp| total_spp|    percent|
# |:---|---------:|---------:|----------:|
# |CR  |       153|     10495|  1.4578371|
# |EN  |       292|     10495|  2.7822773|
# |EX  |        24|     10495|  0.2286803|
# |LC  |      8719|     10495| 83.0776560|
# |NT  |       546|     10495|  5.2024774|
# |VU  |       761|     10495|  7.2510719|


data <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/spp/v2018/_data/iucn_risk_current_2018-1.csv')

data_grouped_2018_1 <- data %>%
  group_by(cat) %>% 
  summarise(count_spp = n()) %>%
  ungroup() %>%
  filter(cat != "DD") %>%
  mutate(total_spp = sum(count_spp)) %>%
  mutate(percent = (count_spp/total_spp)*100)

kable(data_grouped_2018_1)

# |cat | count_spp| total_spp|    percent|
# |:---|---------:|---------:|----------:|
# |CR  |       151|     10141|  1.4890050|
# |EN  |       288|     10141|  2.8399566|
# |EX  |        24|     10141|  0.2366631|
# |LC  |      8369|     10141| 82.5263781|
# |NT  |       556|     10141|  5.4826940|
# |VU  |       753|     10141|  7.4253032|


```


Take a look at Israel: 


```{r}


scores <- read_csv(file.path(here(), "yearly_results/global2021/OHI_final_formatted_scores_2021-11-04.csv"))


spp_status <- scores %>%
  filter(goal == "SPP", dimension == "status", region_id != 0) 
  

## get top ten and bottom ten scores for 2021

DT::datatable(spp_status %>%
  filter(scenario == 2021) %>%
  arrange(-value) %>%
    dplyr::select(goal, dimension, region_name, scenario, value))


reds <-  colorRampPalette(c("#A50026", "#D73027", "#F46D43", "#FDAE61", "#FEE090"), space="Lab")(65)
blues <-  colorRampPalette(c("#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4", "#313695"))(35)
myPalette <-   c(reds, blues)

data <- scores %>%
  filter(dimension == "score") %>%   # focus only on score data
  filter(region_id != 213)  %>% # eliminate Antarctica
  mutate(value = round(value, 0)) %>%
  mutate(region_name = as.character(region_name)) %>%
  group_by(region_id) %>% 
  mutate(meanIndex=mean(value[goal=="Index"])) %>%
  ungroup() %>%
  data.frame() %>%
  filter(goal == "SPP")
  


data_isr <- data %>%
  filter(region_name == "Israel")

data_isr


ggplot(data_isr, aes(y=region_name, x=scenario, fill=value)) + 
  geom_tile() +
  facet_grid(~goal) + 
  scale_fill_gradientn(colours=myPalette, na.value="black") +
  theme(axis.text.x  = element_text(angle=90, vjust=0.5), axis.text.y=element_text(size=10)) +
  ylab("") + 
  xlab("")



data_2019 <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2021/gh-pages/globalprep/spp/v2020/_data/iucn_risk_current_2019-1.csv')



```
