---
title: 'OHI 2017 Results'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../ohiprep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---


```{r data set up, include=FALSE}

#load libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(hwriter)
library(RColorBrewer)
library(knitr)
library(googleVis)
library(ohicore)
library(sp)
library(rgdal)
library(DT)
library(broom)
library(nlme)
library(plotly)

# Set working directory when not knitting:
# setwd("global2017/Results")

goals <- c('Index', 'AO', 'SPP', 'BD', 'HAB', 'CP', 'CS', 'CW', 'ECO', 'LE', 'LIV', 'FIS', 'FP', 'MAR', 'ICO', 'SP', 'LSP', 'NP', 'TR')
goal_names <- data.frame(goal=goals, long_goal=c("Index", 
                                                  "Artisanal opportunities",
                                                  "Species condition (Biodiversity)",
                                                  "Biodiversity",
                                                  "Habitat (Biodiversity)",
                                                  "Coastal protection",
                                                  "Carbon storage",
                                                  "Clean water",
                                                  "Economies",
                                                  "Livelihoods & economies",
                                                  "Livelihoods",
                                                  "Fisheries (Food provision)",
                                                  "Food provision",
                                                  "Mariculture (Food provision)",
                                                  "Iconic species (Sense of place)",
                                                  "Sense of place",
                                                  "Lasting special places (Sense of place)",
                                                  "Natural products",
                                                  "Tourism & recreation"))

## General settings to control
scenario <- "2017" #identify scenario of focus (this can be changed to obtain data for other years)
colorScheme <- 'new'  # color scheme to use on flower plots ("new" = color reflects size score and is not the original rainbow)
saveFile <- 'global2017' #location where files that are created are to be saved

## General files to load
rgn_names <- read.csv('../../eez/layers/rgn_global.csv') %>%
  dplyr::select(region_id = rgn_id, country = label) %>%
  dplyr::mutate(country = as.character(country))


saveDate = '2017-11-20' #date extension on the radical data files that are used for all tables/figures

```

### Trend vs scores
(figure out which regions to label)

```{r trend vs score fig 3}

index <- read.csv("data/scores_eez2017.csv") %>%
  select(region_id, region_name, Index)

vaxis <- index$Index[index$region_id==0]

trend <- read.csv(sprintf("data/trends_%s.csv", scenario)) %>%
  select(region_id, index_trend = Index) %>%
  left_join(index, by= "region_id") %>%
  filter(region_id != 0)


mod <- lm(index_trend ~ Index, data=trend)
summary(mod)

  p <- ggplot2::ggplot(trend, aes(x=Index, y=index_trend)) +
    geom_point(aes(text=paste0("rgn = ", region_name)), shape=19, size=2, color="gray", alpha = 0.75) +
    geom_point(aes(text=paste0("rgn = ", region_name)), shape=19, size=2, color="gray", alpha = 0.75) +
    geom_hline(yintercept = 0, color="red", size=.5, linetype=3) +
    geom_vline(xintercept = vaxis, color="red", size=.5, linetype=3) +
    stat_smooth(method=lm, se=FALSE, color="black", size=0.5) +
    theme_bw() + 
    labs(y="Average change in OHI score per year)", x="OHI score (2017)") 

  plotly_fig <- plotly::ggplotly(p)
  plotly_fig
  
### adding labels
  labels1 <- c("Bosnia and Herzegovina", "Vietnam", "Philippines",
              "Eritrea", "Equatorial Guinea", "Nicaragua", "Turkey", "Somalia", "Costa Rica",
          "Glorioso Islands", "American Samoa", "Croatia",
              "Estonia", "New Zealand", "Bahamas")
  
  labels2 <- c("South Georgia and the South Sandwich Islands", "Republique du Congo")
  
setdiff(labels1, trend$region_name)

trend <- trend %>%
  mutate(label1 = ifelse(region_name %in% labels1, as.character(region_name), NA)) %>%
  mutate(label2 = ifelse(region_name %in% labels2, as.character(region_name), NA)) 
  

  p <- ggplot2::ggplot(trend, aes(x=Index, y=index_trend)) +
    geom_point(shape=19, size=1.75, color="black", alpha = 0.5) +
    geom_text(aes(label=label1), hjust=0, nudge_x=0.4, size=2.2) + 
    geom_text(aes(label=label2), vjust=0, nudge_y=0.1, nudge_x=-5, size=2.2) +
   geom_point(data=filter(trend, region_name %in% label1), aes(x=Index, y=index_trend), shape=19, size=1.75, color="darkorange") +
   geom_point(data=filter(trend, region_name %in% label2), aes(x=Index, y=index_trend), shape=19, size=1.75, color="darkorange") +
    geom_hline(yintercept = 0, color="red", size=.2, linetype=3) +
    geom_vline(xintercept = vaxis, color="red", size=.2, linetype=3) +
      stat_smooth(method=lm, se=FALSE, color="black", size=0.3) +
    theme_bw() + 
    labs(y="Average change in Index score per year", x="OHI score, 2017") 

plot(p)   
ggsave("figures/trend vs score.png", width=7.5, height=5, units=c("in"), dpi=600)
ggsave("figures/trend vs score.tiff", width=6, height=4, units=c("in"), dpi=375)

```


## pairwise comparison of goal scores
```{r pairwise comparisons supplement}
index_2017 <- read.csv("data/scores_eez2017.csv") %>%
  filter(region_id != 0) %>%
  select(-c(region_name, region_id)) %>%
  select(-c(SPP, HAB, ECO, LIV, FIS, MAR, ICO, LSP, Index))

panel.cor <- function(x, y, digits=2, prefix="", cex.cor, ...){
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y, use="na.or.complete"))
  txt <- format(c(r, 0.123456789), digits=digits)[1]
  txt <- paste(prefix, txt, sep="")
  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt, cex = (cex.cor * r + .15)*3)
}

pairs(index_2017,
      lower.panel=panel.smooth, upper.panel=panel.cor, 
      pch=16, cex=.5)
## export as png with 700 x 700 dimensions



#seeing ones were significant
# panel.cor <- function(x, y, digits=2, prefix="", cex.cor) 
# {
#   usr <- par("usr"); on.exit(par(usr)) 
#   par(usr = c(0, 1, 0, 1)) 
#   r <- abs(cor(x, y)) 
#   txt <- format(c(r, 0.123456789), digits=digits)[1] 
#   txt <- paste(prefix, txt, sep="") 
#   if(missing(cex.cor)) cex <- 0.8/strwidth(txt) 
#   
#   test <- cor.test(x,y) 
#   # borrowed from printCoefmat
#   Signif <- symnum(test$p.value, corr = FALSE, na = FALSE, 
#                    cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1),
#                    symbols = c("***", "**", "*", ".", " ")) 
#   
#   text(0.5, 0.5, txt, cex = cex * r) 
#   text(.8, .8, Signif, cex=cex, col=2) 
# }
# pairs(index_2016,
#       lower.panel=panel.smooth, upper.panel=panel.cor)


```

### Carpet plot of trends

```{r carpplot trend supplement}

data <- read.csv(sprintf('../OHI_final_formatted_scores_%s.csv', saveDate)) 

data <- data %>%
  filter(dimension == "score") %>%   # focus only on score data
  filter(region_id != 0) %>%         # this weighted mean includes high seas and Antarctica
  mutate(region_id = ifelse(region_id==300, 0, region_id)) %>%   #convert the 300 (i.e., only eez's averaged to zero)
  filter(region_id <= 250) %>%       # get rid of high seas regions
  filter(region_id != 213)  %>%
  mutate(value = round(value, 0)) %>%
  group_by(region_id) %>% 
  mutate(meanIndex=mean(value[goal=="Index"])) %>%
  ungroup() %>%
  data.frame()
  

trends <- read.csv(sprintf("data/trends_%s.csv", scenario)) %>%
  gather(goal, "value", -(1:2)) %>%
  select(-region_id, region_name = country) %>%
  filter(region_name != "eez_weighted_avg")

region_order <- trends %>%
  filter(goal=="Index") %>%
  arrange(value)

values <-   brewer.pal(11, "RdYlBu")
col.values <- colorRampPalette(values, space = 'Lab')(12)
col.brks  <- c(-100, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 100)

trends$goal <- factor(trends$goal, levels = goals)
trends$region_name <- factor(trends$region_name, levels=region_order$region_name)
trends$trend_category <- cut(trends$value, breaks = col.brks)
  

p <- ggplot(trends, aes(y=region_name, x=goal, fill=trend_category)) +   
  geom_tile(aes(text = paste0("trend = ", value))) +
  scale_fill_manual(values = col.values, na.value="black") +
  theme(axis.text.x  = element_text(angle=90, vjust=0.5)) +
  ylab("") + 
  xlab("") +
  theme_bw()
plot(p)

ggsave("figures/trend_heatplot.png", width = 20, height=25, units="in")
ggplotly(p)

```


### Scores vs. population, HDI, and CHI

```{r pop hdi chi supplement}

index <- read.csv("data/scores_eez2017.csv") %>%
  select(rgn_id = region_id, region_name, Index) %>%
  filter(rgn_id != 0) 

hdi <- read.csv("../../../ohiprep/globalprep/supplementary_information/v2017/HDI_data.csv") %>%
  select(rgn_id, hdi=X2015)

# coastal population
pop <- read.csv("../../../ohiprep/globalprep/mar_prs_population/v2017/output/mar_pop_25mi.csv") %>%
  filter(year == 2017) %>%
  select(rgn_id, coastal_pop = popsum) %>%
  mutate(log_coastal_pop = log(coastal_pop + 1))

## chi data
chi <- read.csv("../../../ohiprep/globalprep/supplementary_information/v2016/CHI_data.csv") %>%
  filter(sp_type == "eez") %>%
  select(rgn_id, chi=mean)


data <- index %>%
  left_join(pop, by="rgn_id") %>%
  left_join(chi, by="rgn_id") %>%
  left_join(hdi, by="rgn_id")

data_noNA <- na.omit(data)

mod1 <- lm(Index ~ chi, data=data_noNA)
summary(mod1)
mod2 <- lm(Index ~ hdi, data=data_noNA)
summary(mod2)
mod3 <- lm(Index ~ log_coastal_pop, data=data_noNA)
summary(mod3)
mod4 <- lm(Index ~ chi + hdi, data=data_noNA)
summary(mod4)
mod5 <- lm(Index ~ log_coastal_pop + hdi, data=data_noNA)
summary(mod5)
mod6 <- lm(Index ~ log_coastal_pop + chi, data=data_noNA)
summary(mod6)
mod7 <- lm(Index ~ log_coastal_pop + chi + hdi, data=data_noNA)
summary(mod7)

AIC(mod1, mod2, mod3, mod4, mod5, mod6, mod7)

mod8 <- lm(chi ~ log_coastal_pop, data=data)
summary(mod8)

mod9 <- lm(hdi ~ log_coastal_pop, data=data)
summary(mod9)

p <- ggplot2::ggplot(data, aes(y=Index, x=hdi)) +
    geom_point(shape=19, size=2, color="gray", alpha = 0.5) +
    theme_bw()  + 
    stat_smooth(method=lm, se=FALSE, color="black", size = 0.5)+
    labs(x="Human Development Index", y="OHI index score") 

plot(p)   
ggsave("figures/OHIvsHDI.png", height=4, width=4.5)

p <- ggplot2::ggplot(data, aes(y=Index, x=chi)) +
    geom_point(shape=19, size=2, color="gray", alpha = 0.5) +
    theme_bw()  + 
    stat_smooth(method=lm, se=FALSE, color="black", size = 0.5)+
    labs(x="Cumulative Human Impact", y="OHI index score") 

plot(p)   
ggsave("figures/OHIvsCHI.png", height=4, width=4.5)

p <- ggplot2::ggplot(data, aes(y=Index, x=log_coastal_pop)) +
    geom_point(shape=19, size=2, color="gray", alpha = 0.5) +
    theme_bw()  + 
    stat_smooth(method=lm, se=FALSE, color="black", size = 0.5)+
    labs(x="Coastal population (ln)", y="OHI index score") 

plot(p)   
ggsave("figures/OHIvsCoastalPop.png", height=4, width=4.5)

p <- ggplot2::ggplot(data, aes(x=chi, y=log_coastal_pop)) +
    geom_point(shape=19, size=2, color="gray", alpha = 0.5) +
    theme_bw()  + 
    stat_smooth(method=lm, se=FALSE, color="black", size = 0.5)+
    labs(x="Coastal population (ln)", y="Cumulative Human Impact") 

plot(p)   
ggsave("figures/CHIvsCoastalPop.png", height=4, width=4.5)


```


### Trend analysis
```{r trend analysis}
### prepare data:
data <- read.csv(sprintf('../OHI_final_formatted_scores_%s.csv', saveDate)) 

data <- data %>%
  filter(dimension == "score") %>%   # focus only on score data
  filter(region_id != 0) %>%         # this weighted mean includes high seas and Antarctica
  filter(region_id <= 250) %>%       # get rid of high seas regions
  filter(region_id != 213) %>%
  filter(!is.na(value))

```

```{r fig 1D hist}

data_lm <- data %>%
  group_by(goal, region_id) %>%
  do(mdl = lm(value ~ scenario, data = .))

#data.frame(glance(data_lm, mdl))
results_lm <- tidy(data_lm, mdl) %>%
  ungroup() %>%
  filter(term == "scenario") %>%
  arrange(goal, estimate) %>%
  left_join(goal_names) %>%
  left_join(rgn_names) %>%
  select(goal=goal, goal_long=long_goal, region_name = country, region_id, average_change_per_year = estimate, p.value) %>%
  data.frame()
# 
# weights <- read.csv("../../eez2016/layers/rgn_area.csv") %>%
#   select(region_id=rgn_id, area_km2)
# 
# results_lm <- results_lm %>%
#   left_join(weights, by="region_id")
# 
# summary_lm <- results_lm %>%
#   group_by(goal, goal_long) %>%
#   summarize(mean=mean(average_change_per_year),
#             mean_wt=weighted.mean(average_change_per_year, w=area_km2))


# color coded histogram of trends

trends_hist <- results_lm %>%
  filter(goal=="Index") %>%
  arrange(average_change_per_year)

values <-   brewer.pal(11, "RdYlBu")
values <- colorRampPalette(values, space = 'Lab')(13)[2:13]
col.brks  <- c(-100, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 100)

trends_hist$colors <- cut(trends_hist$average_change_per_year, breaks=col.brks, include.lowest=TRUE, labels=values)
cols <- as.character(unique(trends_hist$colors))


g <- ggplot(trends_hist, aes(x=average_change_per_year)) +
geom_histogram(aes(fill=colors), bins=25, center=1.01, col="gray") +
scale_fill_manual("", breaks=colors, values=cols, guide=FALSE) +
labs(y="Number of regions", x="Average yearly change") +
#geom_vline(xintercept=0, color="red") +
theme_bw()

print(g)

 ggsave("figures/trend_histogram_color.tiff", width=4, height=3, units=c("in"), dpi=300)
 

```


```{r fig 1B hist}

data_scores <- data %>%
  filter(goal=="Index") %>%
  filter(scenario == 2017) 

reds <-  colorRampPalette(c("#A50026", "#D73027", "#F46D43", "#FDAE61", "#FEE090"), space="Lab")(66)
blues <-  colorRampPalette(c("#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4", "#313695"), space="Lab")(35)
colors <-   c(reds, blues)

col.brks <- seq(0,100, by=1)
col.assign <- cut(col.brks, breaks=col.brks, include.lowest = TRUE)
colors_df <- data.frame(colors_plot=colors, col.assign)
colors_df$col.assign <- as.character(colors_df$col.assign) 

data_scores$col.assign <- cut(data_scores$value, breaks=col.brks, include.lowest=TRUE) 
data_scores$col.assign <- as.character(data_scores$col.assign)

data_scores <- left_join(data_scores, colors_df, by="col.assign") %>%
  mutate(colors_plot = as.character(colors_plot)) %>%
  arrange(value)

cols <- as.character(unique(data_scores$colors_plot))

g <- ggplot(data_scores, aes(x=value)) +
#geom_histogram(aes(fill=colors), bins=25, center=1.01, col="gray") +
geom_histogram(aes(fill=col.assign), bins=31) +  
scale_fill_manual("", values=cols, guide=FALSE) +
xlim(c(0, 100)) +
labs(y="Number of regions", x="Index score") +
theme_bw()

print(g)

 ggsave("figures/score_histogram_color.tiff", width=4, height=3, units=c("in"), dpi=300)
 ggsave("figures/score_histogram_color.png", width=4, height=3, units=c("in"), dpi=300)

```


