
---
title: Description of ohicore functions
author: Melanie Frazier
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    includes:
      in_header: ../../ohiprep/src/R/mystyle.htm
    toc: true
---

###dataprep functions

* **UPDATED, but not incorporated, see test directory** gapfill_georegions: gapfilling with georegion means
* **UPDATED, but not incorporated, see test directory** name_to_rgn: converts country names to rgn_id and deals with sovereign countrys
* **ADDED (Oct 2015)** mapvalues: from dplyr package, provides easy method of changing factor levels

###core organizing/checking data layers functions

* CheckLayers: checks layers.csv to make sure data files exist in layers directory 
* Conf: creates conf object (a list) that has information from config.R and functions.R
* Layers: creates layers object (a list) with all of the raw data layers 
* SelectLayersData: function to extract raw data from layers object

###core calculation functions

**UPDATED (Oct 2015)** CalculateAll:  Primary function used to calculate all the scores (calls a variety of functions)

* **UPDATED (Oct 2015)** CalculatePressuresAll: Calculate pressure
    + CalculatesPressuresScore
    + CalculatePressuresMatrix
* **UPDATED (Oct 2015)** CalculateResilienceAll: Calculate resilience
    + CalculateResilienceScore
    + CalculateResilienceMatrix
* CalculateGoalIndex: Calculate scores
* CalculateSubgoal: Computes a single subgoal
    + CalculateStatusComponent
    + CalculatePressuresComponent
    + CalculateResilienceComponent
* ScoreScaling: functions for scaling data (score.rescale, score.max, score.clamp)
    
###after scores are calculated

* Git related functions
    + read_git_csv: read a csv from git file
    + trace_git_csv: trace value from csv file through history of local Git repository
* Checking/comparing data
    + compare_scores_df: compare 2 scores.csv files and calculate difference
* Reporting
    + **DELETED Oct 2015** PlotFlower: make the flower plots
    + aster: make the flower plots (I think this is the same thing as PlotFlower)
    + **DELETED Oct 2015** ReportScores: part of report generation, but I'm not sure this was ever completed
    + **DELETED Oct 2015** ReportScoresComparison: part of report generation, but I'm not sure this was ever completed (look for report.Rmd in files)

###apps

* shp_to_geojson: save a shape file as GeoJson
* launch_app
* launch_cmp
* write_shortcuts

###unknown how used

* get_scenarios.R: downloads entire repository, not sure why
* zzz: appears to control how packages are downloaded (but doesn't look like anything)
* **DELETED Oct 2015** data: references data from 2012 analysis, but I am not sure what is happening
* **DELETED Oct 2015** PlotChloroPlethMap.R: This doesn't look like anything related to what we are doing
