### Trend

Trend is the proportional change in status predicted to occur in 5 years, based on recent status data. In most cases, this is calculated by estimating the yearly change in status using a linear regression model (i.e., slope estimate) of the five most recent years of status data and multiplying this value by 5 to estimate the change five years into the future.  To determine proportional change, we divide the slope estimate by the status value of the earliest year of data used in the trend calculation.  

In OHI assessments prior to 2016, we calculated trend as the *absolute* change in status predicted to occur in 5 years.  In 2016, we began calculating the *proportional* change by dividing the slope estimate by the status of the earliest year used in the trend calculation.  Although this change rarely had a large effect on trend, or ultimate score values, this method is more consistent with how trend data is incorporated into the likely future status model (Eq. 4.5). If the $\beta$, pressure ($p$), and resilience ($r$) components of the likely future status model are ignored (this assumes the pressure and resilience components fully cancel each other out), the equation becomes: 

$x(1 + trend)$,

where, $x$ is the current status.  Given this, if $x=50$, and we expect trend to increase by 10% over 5 years, then likely future status would be: $50(1 + 0.10) = 55$.

Because status values range from 0-1, Trends typically range from -1.0 to 1.0, and we constrained values to this range if they fell outside it.

For all goals we included the trend estimate, even if the linear model was not statistically significant (i.e., P<0.05). We chose to include these values for two key reasons: 1) we were not trying to predict the future but instead only indicate likely condition. 2) in nearly all cases we did not have sufficient data to conduct more rigorous trend analyses.

In some cases, we were not able to estimate trend using status data due to data limitations.  In these cases, we used alternative methods to estimate trend.  For example, for the species condition subgoal, we converted IUCN trend information (e.g., "increasing", "decreasing", etc.) to numeric values and averaged these for each region. Specific details about trend calculations for each goal are provided in section 5.

We recognize several possible shortcomings in using past trends to estimate likely future status.  We assume a simple linear trend, but this is not always the case due to a variety of variables such as altered pressures and resilience responses, nonlinear patterns in system response, stochastic environmental and biological variability, and simple bounding conditions (status cannot go below zero or above 1.0, and so the trend must level off as it approaches these values).  Also, it is important to note that the same trend value could reflect many different processes. For example, declines due to unsustainable harvest of a resource can look identical to declines due to restrictions placed on resource users to allow the resource to recover. It also may be too short a time frame to determine true trends or the causes of those trends, but the intent here is more about informing the likely near-term trajectory.