### Goal Description

Mariculture measures the ability to reach the highest levels of seafood gained from farm-raised facilities without damaging the ocean’s ability to provide fish sustainably now and in the future. Higher scores reflect high food provisioning in a sustainable manner, while not compromising the water quality in the farmed area and not relying on wild populations to feed or replenish the cultivated species. A score of 100 means that a region is sustainably harvesting the greatest amount of farmed seafood possible based on its own potential.

### Model

Model measures the quantity of sustainably harvested mariculture species per 1% of a regions aquaculture potential. The _species assessed_ are strictly marine species from both the marine and brackish water FAO categories, excluding species not used as a source of food (FAO 2003, Halpern 2012). The _sustainability score_ ($S_{k,r}$_) for each species in each country is based on the Monterey Bay Aquarium Seafood Watch [aquaculture recommendations](https://www.seafoodwatch.org/seafood-recommendations/standards-revision) ([Seafood Watch 2021](https://seafoodwatch.org/)).

### Reference points 

The reference point is 1% of aquaculture potential among all assessed regions. 



