### Goal Description

In many countries the harvest of non-food natural products is important for local economies and can also be traded internationally. The sustainable harvest of these products is therefore an important component of a healthy ocean. This goal assesses the ability of countries to maximize the sustainable harvest of living marine resources, such as seaweeds, fish oil, and fish for the aquarium trade. It does not include bioprospecting which focuses on potential (and largely unknowable and potentially infinite) value rather than current realized value, or non-living products such as oil and gas or mining products which by definition are not sustainable.

### Model & Data 

The goal model measures the harvest level (in metric tons) for a product and the sustainability of that harvest. The _sustabinality factor_ of ornamental fish was accounted for by adjusting its harvest level with a sustainability term based on the intensity of harvest per km2 of coral and/or rocky reef relative to the global maximum (its ‘_exposure_’). The sustainability factor for ornamental fish also includes the ‘_risk_’ that is associated with known unsustainable harvest practices (i.e., the intensity of cyanide fishing for ornamental fish, and any harvest of corals since they are CITES protected species). 

The _sustainability factor_ of seaweeds was based off of the Mariculture Sustainability Index, while the _sustainability factor_ of fish oil was based of of B/Bmsy values derived from our fisheries sub-goal. 

Three different natural products were assessed: ornamental fish, fish oil, and inedible seaweeds and marine plants. Status of sustainable harvest of each product (tonnes) was calculated individually first. The overall goal score weights the status of each product by its proportional value (US dollars) relative to other harvested products. 

### Reference points 

For ornamentals and seaweeds, the reference point is its maximum value (in 2008 USD) achieved in that country, under the assumption that the maximum achieved at any point in time was likely the maximum possible. This creates a reference point internal to each country. For fish oil, the reference point was based off of the B/Bmsy values, where values below one are considered over harvested stocks, and values above 1 are considered under harvested stocks. 
