---
title: "Calculating percent contribution of gapfilling to pressure/resilience components"
author: "Mel"
date: "4/5/201"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
# load libraries
library(tidyr)
library(dplyr)

setwd('/home/frazier/ohi-global/global2015/gapFilling') # comment this out when knitting!!!

# list of regions:
regions <- read.csv('../../../ohiprep/src/LookupTables/eez_rgn_2013master.csv') %>%
  select(region_id = rgn_id_2013) %>%
  filter(region_id < 255) %>%
  filter(region_id != 213) %>%
  arrange(region_id) %>%
  unique()

## also add in the supragoals, which actually do not have resilience calculated for them!
goal_all <- c("FIS", "MAR", "AO",  "TR",  "ICO", "LSP", "CW", "SPP", "NP", "HAB", "CP", "CS", "LIV", "ECO")

```


## General notes
This script calculates the proportion of each goal's pressure and resilience scores that are based on gap-filled data.  All gap-filling is weighted equally.  

I am only focusing on the 2015 data, although some layers have additional years.

I ignore LE/ECO/LIV because we will be changing these data.


## Pressure


```{r pressure, warning=FALSE, message=FALSE}

## data.frame to add pressures:
regions_pressure <- expand.grid(region_id = regions$region_id, goal=goal_all, dimension="pressure")

###########################
## pressures_matrix
###########################
pm <- read.csv("pressures_matrix.csv")
 
p_cats <- data.frame(category =c("po", "hd", "sp", "fp", "cc", "ss"),
                     level = c("environmental", "environmental", "environmental", "environmental", "environmental", "social"))

pm <- pm %>%
  gather("pressure", "p_weight", 4:ncol(pm)) %>%
  filter(!(goal %in% c("LIV", "ECO"))) %>%
  filter(!is.na(p_weight)) %>%
  mutate(category = substring(pressure, 1, 2)) %>%
  left_join(p_cats, by="category") %>%
  group_by(goal, category) %>%
  mutate(max_p_weight = max(p_weight)) %>% # used to weight categories when averaging
  ungroup() %>%
  arrange(goal)


###############################################
## make matrix of pressures gapfilling layers
###############################################

# list of data layers that are needed based on what is in the pressure matrix:
layers <- unique(pm$pressure)

p_layers <- data.frame()

for(layer in layers){ # layer = "fp_com_lb"
  tmp <- read.csv(sprintf('layers/%s.csv', layer)) %>%
    mutate(pressure = layer)
  
  names(tmp)[2] <- "score"
  
  p_layers <- rbind(p_layers, tmp)
}

## check to see if the pressure matrix and layers match
if(length(setdiff(layers, unique(p_layers$pressure))) >0 ){
  warning("some pressure layers appear to be missing")
}


#------------------------------------------------
## first calculate goals with no components:
#------------------------------------------------

# list of goals with no components:
goals_nc <- c("FIS", "MAR", "AO", "TR", "ICO", "LSP", "CW", "SPP")

pm_noComp <- pm[pm$goal %in% goals_nc, ] 

data_noComp <- p_layers %>%
  left_join(pm_noComp, by=c("pressure")) %>%
  arrange(goal, rgn_id)

data_noComp <- data_noComp %>%
  group_by(goal, rgn_id, category, level, max_p_weight) %>%
  summarize(score = weighted.mean(score, p_weight, na.rm=TRUE)) %>%
  ungroup()

# average across categories weighted by maximum pressure matrix values within each category (see eq 9 in 2012 paper)
data_noComp <- data_noComp %>%
  group_by(goal, rgn_id, level) %>%
  summarize(score = weighted.mean(score, max_p_weight, na.rm=TRUE)) %>%
  ungroup()


# average social and environmental pressures
data_noComp <- data_noComp %>%
  group_by(goal, rgn_id) %>%
  summarize(score = mean(score, na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(dimension = "pressure") %>%
  select(goal, dimension, region_id = rgn_id, score) %>%
  data.frame()


#------------------------------------------------
## second calculate habitat related goals with components:
#------------------------------------------------

## create blank dataset
scores_pressure_habs <- data.frame()

for(goal in c('CS', 'CP', 'HAB')){ #goal <- "CS"

# the new pressure matrix specific to each goal and region based on habitat weights
# I generated the weights for each region using the CalculatePressuresAll function in ohicore
  
pm_hab <- read.csv(sprintf('pressure_matrix_%s.csv', goal)) 
names(pm_hab)[1] <- "rgn_id"

pm_hab <- pm_hab %>%
  gather("pressure", "p_weight", 2:ncol(pm_hab)) %>%
  filter(!is.na(p_weight)) %>%
  mutate(category = substring(pressure, 1, 2)) %>%
  left_join(p_cats, by="category") %>%
  group_by(rgn_id, category) %>%
  mutate(max_p_weight = max(p_weight)) %>% # used to weight categories when averaging
  ungroup()

# merge adjusted weights with p_layers data; average within each category, weighting by pressure matrix values (adjusted for habitats)
# these are actually summed for pressures calculation
p_layers_goal <- p_layers %>%
  left_join(pm_hab, by=c("rgn_id", "pressure")) %>%
  group_by(rgn_id, category, level, max_p_weight) %>%
  summarize(score = weighted.mean(score, p_weight, na.rm=TRUE)) %>%
  ungroup()
  
# average across categories weighted by maximum pressure matrix values within each category (see eq 9 in 2012 paper)
p_layers_goal <- p_layers_goal %>%
  group_by(rgn_id, level) %>%
  summarize(score = weighted.mean(score, max_p_weight, na.rm=TRUE)) %>%
  ungroup()

# average social and environmental pressures
p_layers_goal <- p_layers_goal %>%
  group_by(rgn_id) %>%
  summarize(score = mean(score, na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(dimension = "pressure") %>%
  mutate(goal = goal) %>%
  select(goal, dimension, region_id = rgn_id, score) %>%
  data.frame()
scores_pressure_habs <- rbind(scores_pressure_habs, p_layers_goal)
}


#------------------------------------------------
## third calculate NP:
#------------------------------------------------

pm_np <- pm[pm$goal == "NP", ] %>%
  mutate(goal = paste(goal, component, sep=" ")) %>%
  group_by(goal, category) %>%
  mutate(max_p_weight = max(p_weight)) %>%
  arrange(goal, category) %>%
  ungroup()

# merge with p_layers data and average according to pressure category for each region
p_layers_goal <- pm_np %>%
  left_join(p_layers, by="pressure") %>%
  filter(!is.na(score)) %>%
  group_by(rgn_id, goal, category, level, max_p_weight) %>%
  summarize(score = weighted.mean(score, p_weight, na.rm=TRUE)) %>%
  ungroup()

# average across categories weighted by maximum pressure matrix values within each category (see eq 9 in 2012 paper)
p_layers_goal <- p_layers_goal %>%
  group_by(rgn_id, goal, level) %>%
  summarize(score = weighted.mean(score, max_p_weight, na.rm=TRUE)) %>%
  ungroup()


# average social and environmental pressures
p_layers_goal <- p_layers_goal %>%
  group_by(rgn_id, goal) %>%
  summarize(score = mean(score, na.rm=TRUE)) %>%
  separate(goal, c("goal", "product"), sep=" ") %>%
  ungroup() 

## get np weights to weight contribution of each component to overall NP score
product_weights <- read.csv('np_harvest_product_weight.csv')

if(length(setdiff(p_layers_goal$product, product_weights$product))>0){
  warning("products in weight file and matrix do not match")
}

NP_scores <- p_layers_goal %>%
  left_join(product_weights) %>%
  filter(!is.na(weight)) %>%
  group_by(rgn_id) %>%
  summarize(score = weighted.mean(score, weight))%>%
  mutate(dimension = "pressure") %>%
  mutate(goal = 'NP') %>%
  select(goal, dimension, region_id = rgn_id, score) %>%
  data.frame()


#------------------------------------------------
## bind all the scores and final formatting
#------------------------------------------------

combined <- rbind(NP_scores, scores_pressure_habs, data_noComp) 

pressure <- regions_pressure %>%
  left_join(combined, by=c("region_id", "goal", "dimension")) %>%
  select(goal, dimension, region_id, score)

```


## Resilience

```{r resilience, warning=FALSE, message=FALSE}

## data.frame to add pressures:
regions_resilience <- expand.grid(region_id = regions$region_id, goal=goal_all, dimension="resilience")

###########################
## resilience matrix
###########################

# weights file:
weights <- read.csv("resilience_weights.csv") %>%
  select(resilience=layer, category = type, weight)

# matrix file:
rm <- read.csv("resilience_matrix.csv", strip.white = TRUE, na.strings = c("", " "), stringsAsFactors = FALSE)
 
rm <- rm %>%
  gather("resilience", "r_weight", 3:ncol(rm)) %>%
  filter(!(goal %in% c("LIV", "ECO"))) %>%
  filter(!is.na(r_weight)) %>%
  left_join(weights, by="resilience") %>%
  select(goal, component, resilience, category, weight)
  
category_weights <- data.frame(category = c("environmental", "regulatory", "social"),
                               category_major = c("environmental", "environmental", "social"))

###############################################
## make matrix of resilience gapfilling layers
###############################################

# list of data layers that are needed based on what is in the pressure matrix:
layers <- unique(rm$resilience)

r_layers <- data.frame()

for(layer in layers){ # layer = "cites"
  tmp <- read.csv(sprintf('layers/%s.csv', layer)) %>%
    mutate(resilience = layer)
  
  names(tmp)[2] <- "score"
  
  r_layers <- rbind(r_layers, tmp)
}

## check to see if the pressure matrix and layers match
if(length(setdiff(layers, unique(r_layers$resilience))) >0 ){
  warning("some pressure layers appear to be missing")
}


#------------------------------------------------
## first calculate goals except NP
## (components are dealt with differently in NP)
#------------------------------------------------

# list of goals with no components:
goals_nc <- c("FIS", "MAR", "AO", "TR", "ICO", "LSP", "CW", "SPP", "HAB", "CP", "CS")

rm_noComp <- rm[rm$goal %in% goals_nc, ] %>%
  select(-component) %>%
  unique() %>%                      # this is getting the unique resilience layers used across all HAB/CP/CS components
  arrange(goal)

data_noComp <- r_layers %>%
  left_join(rm_noComp, by=c("resilience")) %>%
  filter(!is.na(weight)) %>%
  arrange(goal, rgn_id) %>%
  group_by(goal, rgn_id, category) %>%
  summarize(score = weighted.mean(score, weight, na.rm=TRUE)) %>%
  ungroup()

# average within major categories (environmental and regulatory)
data_noComp <- data_noComp %>%
  left_join(category_weights, by="category") %>%
  group_by(goal, rgn_id, category_major) %>%
  summarize(score = mean(score, na.rm=TRUE)) %>%
  ungroup()

# average across major categories (environmental and social)
data_noComp <- data_noComp %>%
  group_by(goal, rgn_id) %>%
  summarize(score = mean(score, na.rm=TRUE)) %>%
  ungroup()

data_noComp <- data_noComp %>%
  mutate(dimension = "resilience") %>%
  mutate(goal = goal) %>%
  select(goal, dimension, region_id = rgn_id, score) %>%
  data.frame()

#------------------------------------------------
## second calculate NP goal
#------------------------------------------------

rm_np <- rm[rm$goal == 'NP', ] %>%
  mutate(goal = paste(goal, component, sep=" ")) %>%
  left_join(r_layers, by="resilience") %>%
  filter(!is.na(score)) %>% 
  group_by(goal, rgn_id, category) %>%
  summarize(score = weighted.mean(score, weight, na.rm=TRUE)) %>%
  ungroup()

# average within major categories (environmental and regulatory)
rm_np <- rm_np %>%
  left_join(category_weights, by="category") %>%
  group_by(goal, rgn_id, category_major) %>%
  summarize(score = mean(score, na.rm=TRUE)) %>%
  ungroup()

# average across major categories (environmental and social)
rm_np <- rm_np %>%
  group_by(goal, rgn_id) %>%
  summarize(score = mean(score, na.rm=TRUE)) %>%
  ungroup() %>%
  separate(goal, c("goal", "product"), sep=" ")
  

## get np weights to weight contribution of each component to overall NP score
product_weights <- read.csv('np_harvest_product_weight.csv')

if(length(setdiff(unique(rm_np$product), unique(product_weights$product)))!=0){
  warning("Some NP products are not included in np_harvest_product_weight.csv")
}

NP_scores <- rm_np %>%
  left_join(product_weights, by=c("product", "rgn_id")) %>%
  filter(!is.na(weight)) %>%
  group_by(rgn_id) %>%
  summarize(score = weighted.mean(score, weight))%>%
  mutate(dimension = "resilience") %>%
  mutate(goal = 'NP') %>%
  select(goal, dimension, region_id = rgn_id, score) %>%
  data.frame()


#------------------------------------------------
## bind all the scores and final formatting
#------------------------------------------------

combined <- rbind(NP_scores, data_noComp) 

resilience <- regions_resilience %>%
  left_join(combined, by=c("region_id", "goal", "dimension")) %>%
  select(goal, dimension, region_id, score)


```


```{r combine and check}

## read in score data, if status is NA for a goal than pressure should be as well

p_r <- rbind(pressure, resilience)

# should be 18 goals
if(length(table(p_r$goal)) != 14){
  stop('There are not 14 goals/subgoals')
}

# check for two dimensions
if(length(table(p_r$dimension))!=2){
  stop('resilience or pressure is missing')
}

# every goal should have a status and trend
if(sum(is.na(table(p_r$goal, p_r$dimension))) > 0 ){
  stop('One or more goals is missing the pressure/resilience dimension')
}


## make sure scores are calculated on the same scale
if(min(p_r$score, na.rm=TRUE) < 0 | max(p_r$score, na.rm=TRUE) > 1) {
  stop('Scores are outside 0 to 1 range...check this')
}



## append data to scores
scores <- read.csv('scores.csv')

scores <- rbind(scores, p_r)
write.csv(scores, "scores.csv", row.names=FALSE)




```

