---
title: "Mapping RAM data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
  pdf_document:
    toc: true
---

```{r setup, include=FALSE, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(sf)

dir_M             <- c('Windows' = '//mazu.nceas.ucsb.edu/ohi',
                       'Darwin'  = '/Volumes/ohi',    ### connect (cmd-K) to smb://mazu/ohi
                       'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]

#load OHI regions
rgns <-  sf::st_read(dsn = "~/github/ohiprep_v2018/globalprep/spatial/v2015/downres", layer = "rgn_eez_gcs_med_res")
```

```{r}

#region details to help us filter by country name rather than ID
rgn_deets <- read_csv("https://raw.github.com/OHI-Science/ohiprep_v2018/gh-pages/globalprep/supplementary_information/v2018/rgn_details.csv")

#load b/bmsy data
bbmsy <- read_csv("~/github/ohi-global/eez/layers/fis_b_bmsy.csv") %>%
  mutate(group = 
           case_when(
             bbmsy < 0.8 ~ "overfished",
             bbmsy >= 0.8 & bbmsy <= 1.45 ~ "fully exploited",
             bbmsy > 1.45 ~ "underfished"
           ))

#load catch data by country
catch <- read_csv("~/github/ohi-global/eez/layers/fis_meancatch.csv") %>%
  separate(stock_id_taxonkey, into = c("stock_id", "taxonkey"), sep = "_(?=[:digit:])")


combine <- bbmsy %>% 
  full_join(catch)

```

Percent of stocks w/ assessment

```{r}
#we want total number of stocks, and number of stocks where !is.na(bbmsy)

prop_stocks_w_ass <- combine %>%
  mutate(assessed = ifelse(!is.na(bbmsy), 1, 0)) %>%
  group_by(rgn_id, year) %>%
  mutate(tot_stocks = length(unique(stock_id)),
         ass_stocks = sum(assessed)) %>%
  ungroup() %>%
  mutate(prop_stocks = ass_stocks/tot_stocks) %>%
  select(rgn_id, year, prop_stocks) %>%
  distinct()
```

Plot the most recent year (2015)

```{r}
#first add data to rgns
map_stock_prop <- rgns %>%
  left_join(prop_stocks_w_ass) %>%
  filter(year == 2015)

ggplot(map_stock_prop) +
  geom_sf(aes(fill = prop_stocks), size = 0.1) +
  theme_minimal() +
  ggtitle("2015") +
  scale_fill_gradientn("Prop. of stocks assessed", colors = RColorBrewer::brewer.pal(10, "RdYlBu")) +
  coord_sf(datum = NA) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")
```


Proportion of catch w/ assessment

```{r}
catch_prop_ass <- combine %>%
  mutate(assessed = ifelse(!is.na(bbmsy), 1, 0)) %>%
  group_by(rgn_id, year) %>%
  mutate(tot_catch = sum(mean_catch)) %>%
  ungroup() %>%
  group_by(rgn_id, year, assessed) %>%
  mutate(c = sum(mean_catch)) %>%
  ungroup() %>%
  mutate(catch_ass_prop = c/tot_catch) %>%
  select(rgn_id, year, assessed, catch_ass_prop) %>%
  distinct() %>%
  filter(assessed == 1,
         year == 2015)
  

map_catch_prop <- rgns %>%
  left_join(catch_prop_ass)
  
ggplot(map_catch_prop) +
  geom_sf(aes(fill = catch_ass_prop), size = 0.1) +
  ggtitle("2015") +
  theme_minimal() +
  scale_fill_gradientn("Prop. of catch assessed", colors = RColorBrewer::brewer.pal(10, "RdYlBu")) +
  coord_sf(datum = NA) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")
```


Let's look at the gap-filled stock score used for each country. T

```{r}
gf <- read_csv("~/github/ohi-global/eez/temp/FIS_summary_gf.csv") %>%
  filter(year == 2018,
         gapfilled == 1,
         taxon_key > 599999) %>%
  select(region_id, score) %>%
  distinct() %>%
  left_join(rgn_deets, by = c("region_id" = "rgn_id"))

#map the stock score used for gapfilling missing catch

map_gf <- rgns %>%
  left_join(gf, by = c("rgn_id" = "region_id"))

ggplot(map_gf) +
  geom_sf(aes(fill = score), size = 0.1) +
  ggtitle("Most recent year") +
  theme_minimal() +
  scale_fill_gradientn("Stock score used to gapfill \n(w/o taxonomic penalties)", colors = RColorBrewer::brewer.pal(10, "RdYlBu")) +
  coord_sf(datum = NA) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")
```


Amount of catch from higher taxonomic levels

```{r, fig.height=7, fig.width = 8}
high_tax <- read_csv("~/github/ohi-global/eez/temp/FIS_summary_gf.csv") %>%
  filter(year == 2018) %>%
  mutate(taxon_level = substr(taxon_key, 1, 1)) %>%
  group_by(region_id, taxon_level) %>%
  summarize(catch = sum(catch)) %>%
  ungroup() %>%
  group_by(region_id) %>%
  mutate(total_catch = sum(catch)) %>%
  ungroup() %>%
  mutate(tax_catch_prop = catch/total_catch,
         level = case_when(
           taxon_level == 1 ~ "1: Marine animals, Scombroids",
           taxon_level == 2 ~ "2: Class(Cephalopoda, Holothuroidea)",
           taxon_level == 3 ~ "3: Order (Perciformes, Gadiformes)",
           taxon_level == 4 ~ "4: Family (Scorpaenidae, Lutjanidae)",
           taxon_level == 5 ~ "5: Genus (Penaeus, Sphyrna)",
           taxon_level == 6 ~ "6: Species (Scomberomorus lineolatus)"
         )
  )


map_taxon_level_catch <- rgns %>%
  left_join(high_tax, by = c("rgn_id" = "region_id")) %>%
  filter(!is.na(tax_catch_prop))

ggplot(map_taxon_level_catch) +
  geom_sf(aes(fill = tax_catch_prop), size = 0.1) +
  ggtitle("Proportion of catch by taxonomic level for the most recent year") +
  theme_minimal() +
  scale_fill_gradientn("Proportion of total catch", colors = RColorBrewer::brewer.pal(10, "RdYlBu")) +
  coord_sf(datum = NA) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "bottom") +
  facet_wrap(~level, nrow = 3)

```

Look at countries that have more than 50% of catch coming from taxonomic level 1 (lowest possible)
```{r}
low_tax <- filter(high_tax, taxon_level == 1, tax_catch_prop > 0.5) %>% 
  left_join(rgn_deets, by = c("region_id" = "rgn_id"))

unique(low_tax$rgn_nam)
```







