---
output: html_document
---

## Food Provision: Fisheries

```{r, child='goals/FIS.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]().   
<!--- For goal model code, click [here](link to functions.r in specific commit/release). --->  

---- 

## Food Provision: Mariculture

```{r, child='goals/MAR.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Artisanal Fishing Opportunity 

```{r, child='goals/AO.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Natural Products

```{r, child='goals/NP.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()   
<!--- For goal model code, click [here](link to functions.r in specific commit/release). --->  

---- 

## Carbon Storage

```{r, child='goals/CS.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Tourism & Recreation

```{r, child='goals/TR.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Livelihoods & Economies: Livelihoods

```{r, child='goals/LIV.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Livelihoods & Economies: Economies

```{r, child='goals/ECO.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Sense of Place: Iconic Species

```{r, child='goals/ICO.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Sense of Place: Lasting Special Places

```{r, child='goals/LSP.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Clean Waters: Nutrients

```{r, child='goals/NUT.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Clean Waters: Trash

```{r, child='goals/TRA.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Clean Waters: Contaminants

```{r, child='goals/CON.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()

---- 

## Biodiversity

```{r, child='goals/BD.Rmd', results='asis', echo=FALSE}
```

[**Full data preparation information and code**]()
