## Food Provision

One of the most fundamental services the ocean provides people is the provision of seafood. From meeting the basic nutritional needs of over half of the world’s population to being sold in high-end sushi restaurants, seafood is an important benefit of healthy oceans. This goal measures the amount of seafood sustainably harvested within an EEZ or region through any means for use primarily in human consumption and thus includes wild-caught commercial fisheries, mariculture, artisanal-scale and recreational fisheries. Importantly, seafood harvest using unsustainable fishing practices or catch levels is penalized, as well as underexploitation of a sustainable resource as the goal aims to maximize the amount of sustainably produced seafood from wild or cultured stocks. Because we do not track where the fish go after being caught or produced, this goal does not aim to measure food security for the population of a given country, but instead measures the food provided from its waters.

The status of the food provision goal is calculated as the mean of the fisheries and mariculture subgoals, weighted by their relative contribution in tonnes to food production for each region. 