## Livelihoods and economies

Due to discontinued and non-updated source datasets, we have not updated the status of this goal since 2013 (changes across scenario years after 2013 are due to changes in pressures/resilience).  

The jobs and revenue produced from marine-related industries are clearly of huge value to many people, even those who do not directly participate in the industries but value community identity, tax revenue, and indirect economic and social impacts of a stable coastal economy. 

This goal is composed of two equally important sub-goals, livelihoods and economies, which are assessed across as many marine-related sectors as possible (Table 6.8). Livelihoods includes two equally important sub-components, the number of jobs, which is a proxy for livelihood quantity, and the per capita average annual wages, which is a proxy for job quality. Economies is composed of a single component, revenue. We track the two halves of this goal separately because the number and quality of jobs and the amount of revenue produced are both of considerable interest to stakeholders and governments, and could show very different patterns in some cases (e.g., high revenue sectors do not necessarily provide large employment opportunities). The status of the livelihoods and economies goal is the average of the livelihoods and economies subgoals. 

The total value of economic industries cannot be captured fully by measuring only the jobs and revenue generated directly by those industries, since activity in the direct industry stimulates additional jobs and revenue in related industries. For example, the fishing industry provides direct jobs to fishers, indirect jobs to fishing gear manufacturing companies, and induced jobs to the restaurants and movie theaters where those manufacturing employees spend their income. In the case of tourism, data describing total jobs and revenue (direct plus indirect and induced) were available from the primary data source, and so we used that information as the best estimate of total employment and total revenue for that sector. For all other sectors we used sector- and development status-specific multipliers derived from the literature to estimate total job or revenue impacts. We did not apply multiplier values to wages since the cascading effects of earned income are more contentious.  We assumed that sector-specific job and revenue multipliers are static and globally consistent, but distinct for developed versus developing countries (when such information was available), because we do not have data to resolve temporal or regional differences (Table 6.9). Countries were classified as developed or developing using the Human Development Index (HDI, @undp_human_2010), with all countries identified as “very high human development” classified as developed and all others as developing. We classified regions not assessed by the HDI by compiling information used to calculate the HDI score (schooling, life expectancy and per capita Gross National Income statistics).

For a job or wage sector to be included in our assessment it needed to report at least two time points and have data for all or most coastal regions (reported separately, not as a single global number). However, a sector did not need to have data for all three measures – jobs, wages, and revenue – as this would have eliminated almost every sector. Consequently, the sectors that comprise each of the three measures differ (Table 6.8) and there is variation across regions in which sectors and measures comprise the status score (because of gaps in datasets and the fact that not all sectors exist in all countries). If a region only had one data layer (a single sector for only one measure), a status score was not calculated for that region and instead, a regional average was applied. We used a weighted average of the region's UN geopolitical region; revenue values were weighted by each region’s GDP, jobs were weighted by each region’s workforce size, and wages were unweighted.

A number of sectors were not included primarily because sufficient data do not exist. In the future, particularly in finer scale applications, it would be desirable to include these sectors, including (but not limited to) ecotourism (beyond just cetacean watching), sailing/kayaking/boating, surfing/kiteboarding, etc., offshore wind and wave energy, navigation assistance, safety and security, coastal development, scientific research, and restoration and conservation.

**Table 6.9. Livelihoods and economies sectors.** 
Sectors for which data were available for each component of the livelihoods and economies goal.

|Sector| Jobs data | Wages data | Revenue data |
|---|---|---|---|
|Tourism | X | X |  X |
|Commercial fishing | X | X | X |
|Marine mammal watching | X |  |  |
|Aquarium fishing| | | X |
|Wave & renewable energy | X | | X|
|Mariculture | X | | X |
|Transportation & shipping | | X | |
|Ports & harbors|  | X |  |
|Ship & boatbuilding|  | X | |


**Table 6.10. Sector multipliers.** 
Sector-specific multipliers used to calculate total jobs and total revenue created by sector-based employment in developing and developed nations. N/A (not applicable) indicates that total employment or total revenue (direct plus indirect and induced) data were provided by primary data source, eliminating the need for a multiplier value. ND indicates no data available for that sector.

| | Developed Countries | | Developing Countries| |
|---|---|---|---|---|
|**Sector**| **Jobs** | **Revenue** | **Jobs** | **Revenue** |
|Tourism | N/A | N/A | N/A | N/A |
|Commercial fishing | 1.582 | 1.568 | 1.582 | 1.568 |
|Marine mammal watching | 1.915 | 1.0 | 1.915 | 1.0 |
|Aquarium fishing | ND | 1.568 | ND | 1.568 |
|Wave & tidal energy | 1.88 | 1.652 | 1.88 | 1.652 |
|Mariculture | 2.7 | 2.377 | 1.973 | 1.59 |

This goal aims to maintain coastal livelihoods and economies (i.e., avoid the loss of, coastal and ocean-dependent jobs and revenues), while also maximizing livelihood quality (relative wages). It does not attempt to capture any aspects of job identity (i.e., the reputation, desirability or other social or cultural perspectives associated with different jobs), although one can examine the component parts that make up this goal to evaluate individual sectors and infer implications for job identity. We make the assumption that all marine-related jobs are equivalent, such that, for example, a fisherman could transition to a job in mariculture or ship-building without affecting the score of this goal. While job identity has social and cultural value, there are not adequate data to track individual workers and assess their job satisfaction on a global scale. We also do not include any measure of petroleum extraction, as we do not consider these practices to be related to the biophysical state of the system and, because they rely on a non-renewable resource, they are inherently unsustainable. Furthermore, because of data constraints, this goal does not provide more credit for sectors or economic activities that are more ecologically sustainable. Future, finer scale applications of the Index may incorporate these key considerations.


Gaps were filled in the adjustment datasets (national GDP and national employment) by first determining the average metric value (e.g., average employment rate) in UN geopolitical regions (@united_nations_statistics_2013) for each year based on all countries in that region for which there were data. Using these regional average time series, we fit nonlinear models to the adjustment data. Using the model fit, we determined the slope between each year. To fill in missing data points in country time series, we applied the slope (percent change in the metric) between the missing year and the following year (or previous year, if necessary). We prioritized filling in backwards (e.g., if a country has data from 2006 and 2008, to fill in 2007, one would use the regional delta between 2008 and 2007), but filled forwards when there were no data for a subsequent year.